import type { Article } from "@/lib/articles";

export interface ArticleFAQItem {
  question: string;
  answer: string;
}

// Curated FAQ overrides for key high-traffic articles
const CURATED_ARTICLE_FAQS: Record<string, ArticleFAQItem[]> = {
  "best-ai-short-form-video-repurposing-tools": [
    {
      question: "Which AI short-form repurposing tool is best for YouTube creators and podcasters?",
      answer: "Opus Clip is our top recommendation for long-form podcasters and YouTubers because of its automated AI virality score, auto-face centering, and hook detection. Descript is the best alternative if you require full transcript-based timeline editing."
    },
    {
      question: "Are there free AI tools to convert long videos into shorts?",
      answer: "Most platforms including Opus Clip and Captions provide free trial credits or freemium watermarked tiers. Descript offers a free tier with 1 transcription hour per month."
    },
    {
      question: "Do AI video repurposing tools automatically add captions and b-roll?",
      answer: "Yes, modern tools like Submagic and Opus Clip automatically transcribe speech, generate animated word-by-word captions with 99% accuracy, and insert relevant stock b-roll and sound effects based on spoken keywords."
    },
    {
      question: "Can short-form videos generated by AI be monetized on TikTok and YouTube Shorts?",
      answer: "Yes. YouTube and TikTok permit monetization of AI-edited short-form content as long as you own the underlying rights to the source footage and provide substantial creative value through editing, commentary, or curation."
    }
  ],
  "best-ai-coding-assistants-2026": [
    {
      question: "What is the best AI coding assistant in 2026?",
      answer: "Cursor and GitHub Copilot are the industry leaders. Cursor excels with full codebase context, multi-file edits, and agentic workflows, while GitHub Copilot offers seamless native integration across VS Code and JetBrains IDEs."
    },
    {
      question: "Are AI code assistants safe for proprietary and enterprise codebases?",
      answer: "Yes, provided you choose enterprise plans (such as GitHub Copilot Enterprise or Cursor Business) with zero-retention policies ensuring your private code is never used to train public models."
    },
    {
      question: "Can AI coding assistants replace software engineers?",
      answer: "No. AI coding assistants automate boilerplate, suggest completions, and speed up debugging, but engineers remain essential for architecture design, edge-case analysis, and systems verification."
    }
  ]
};

export function getBlogArticleFaqs(article: Article): ArticleFAQItem[] {
  // 1. Check curated overrides
  if (CURATED_ARTICLE_FAQS[article.slug]) {
    return CURATED_ARTICLE_FAQS[article.slug];
  }

  // 2. Check if article has embedded faqs property
  if ((article as any).faqs && Array.isArray((article as any).faqs) && (article as any).faqs.length > 0) {
    return (article as any).faqs;
  }

  // 3. Generate high-quality contextual FAQs tailored to this guide's topic & category
  const title = article.title.replace(/\s*\(\d{4}[^)]*\)/g, "").trim();
  const category = article.category || "AI Software";

  return [
    {
      question: `What are the top solutions evaluated in this ${category} guide?`,
      answer: `This guide analyzes the most dependable solutions in the ${category.toLowerCase()} space based on benchmark testing, feature depth, and real-world performance. Browse the comparison table and detailed reviews above to identify the ideal platform for your workflow.`
    },
    {
      question: `Are there free or freemium tools included in this guide?`,
      answer: `Yes, many of the featured platforms provide free starter tiers, trial periods, or community plans so you can test capabilities before committing to a paid subscription.`
    },
    {
      question: `How does AIToolsHaven test and rank these ${category.toLowerCase()} tools?`,
      answer: `Our team evaluates platforms using a structured E-E-A-T benchmark methodology: we test ease of onboarding, prompt response accuracy, integrations, pricing transparency, and real-world team productivity impact.`
    },
    {
      question: `How do I select the right tool from this guide?`,
      answer: `Start by identifying your non-negotiables—such as budget, API availability, learning curve, and existing tech stack compatibility. Test the free tiers of your top two candidates using your everyday production tasks.`
    }
  ];
}
