export const opportunities = [
    {
        title: "Faceless YouTube",
        description: "Grow a YouTube channel without showing your face on camera.",
        icon: "smart_display",
        slug: "faceless-youtube",
        difficulty: "Beginner",
        roi: "High Revenue",
        color: "from-emerald-400 to-teal-600",
    },
    {
        title: "AI Influencers",
        description: "Design virtual creators for Instagram, TikTok, and X.",
        icon: "photo_camera_front",
        slug: "ai-influencers",
        difficulty: "Advanced",
        roi: "High Growth",
        color: "from-purple-500 to-indigo-600",
    },
    {
        title: "Vibe Coding",
        description: "Build apps and websites faster with AI assistants.",
        icon: "code",
        slug: "vibe-coding",
        difficulty: "Intermediate",
        roi: "Fast Output",
        color: "from-cyan-400 to-blue-600",
    },
    {
        title: "AI Automation Agency",
        description: "Help other businesses automate their busywork.",
        icon: "automation",
        slug: "ai-workflows",
        difficulty: "Intermediate",
        roi: "$5k+/mo",
        color: "from-orange-400 to-amber-600",
    },
    {
        title: "AI UGC Creator",
        description: "Produce short-form video content for brands using AI.",
        icon: "movie",
        slug: "make-money-online",
        difficulty: "Beginner",
        roi: "High Demand",
        color: "from-rose-400 to-red-600",
    },
    {
        title: "AI Consulting",
        description: "Teach teams how to adopt AI into their daily workflows.",
        icon: "business_center",
        slug: "business-growth",
        difficulty: "Advanced",
        roi: "High Margin",
        color: "from-slate-700 to-slate-900",
    },
];