import fs from 'fs';
import path from 'path';

const projectDir = process.cwd();
const toolsJsonPath = path.join(projectDir, 'data', 'tools.json');

const tools: any[] = JSON.parse(fs.readFileSync(toolsJsonPath, 'utf8'));

// Batch 2 seed tools: Categories 4, 5, 6
const batch2Tools = [
  // 1. ai-code-review-security
  {
    name: 'SonarQube AI',
    slug: 'sonarqube-ai',
    tagline: 'Static analysis and continuous code inspection finding bugs and security vulnerabilities',
    description: 'SonarQube analyzes 30+ programming languages to detect code smells, security hotspots, and vulnerabilities in pull requests before deployment.',
    websiteUrl: 'https://sonarsource.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Code Quality', 'Security Scan', 'Static Analysis'],
    additionalCategories: ['ai-code-review-security']
  },
  {
    name: 'DeepSource',
    slug: 'deepsource-ai',
    tagline: 'Automated code health and security scanner fixing issues automatically',
    description: 'DeepSource automatically detects and fixes bug risks, anti-patterns, performance bottlenecks, and security issues across your codebase with Autofix PRs.',
    websiteUrl: 'https://deepsource.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Code Health', 'Autofix', 'Security Audit'],
    additionalCategories: ['ai-code-review-security']
  },
  {
    name: 'GitGuardian',
    slug: 'gitguardian-ai',
    tagline: 'Automated secrets detection and security compliance monitoring for developers',
    description: 'GitGuardian scans code repositories in real-time to prevent secret leaks, exposed API keys, and sensitive database credentials in CI/CD pipelines.',
    websiteUrl: 'https://gitguardian.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Secrets Detection', 'DevSecOps', 'API Security'],
    additionalCategories: ['ai-code-review-security']
  },
  {
    name: 'Semgrep AI',
    slug: 'semgrep-ai',
    tagline: 'Fast, lightweight static analysis for finding and preventing code vulnerabilities',
    description: 'Semgrep is an ultra-fast code analysis engine that combines AST matching and AI to enforce custom security rules and catch supply chain risks.',
    websiteUrl: 'https://semgrep.dev',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Static Analysis', 'AppSec', 'Vulnerability Scanner'],
    additionalCategories: ['ai-code-review-security']
  },

  // 2. ai-figma-to-code
  {
    name: 'Dualite',
    slug: 'dualite-dev',
    tagline: 'Convert Figma designs into production-ready React, Tailwind, and Flutter code',
    description: 'Dualite provides designers and frontend engineers with 1-click conversion from Figma components to responsive, maintainable code with zero refactoring.',
    websiteUrl: 'https://dualite.dev',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Figma to React', 'Flutter Code', 'Design Handoff'],
    additionalCategories: ['ai-figma-to-code']
  },
  {
    name: 'Polipo',
    slug: 'polipo-io',
    tagline: 'AI design-to-code compiler transforming Figma files into responsive web components',
    description: 'Polipo analyzes design tokens, layout hierarchy, and component variants in Figma to generate semantic HTML, CSS, and clean React code.',
    websiteUrl: 'https://polipo.io',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Design System', 'Figma to Code', 'Frontend Automation'],
    additionalCategories: ['ai-figma-to-code']
  },
  {
    name: 'Quest AI',
    slug: 'quest-ai',
    tagline: 'Generate clean React and Next.js code directly from Figma designs with logic bindings',
    description: 'Quest AI translates Figma frames into accessible React components, hooking up state management, API endpoints, and animations seamlessly.',
    websiteUrl: 'https://quest.ai',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['React Generator', 'Figma Plugin', 'Next.js UI'],
    additionalCategories: ['ai-figma-to-code']
  },
  {
    name: 'CopyCat',
    slug: 'copycat-dev',
    tagline: 'Fast Figma to React component generator with pixel-perfect design fidelity',
    description: 'CopyCat converts Figma mockups into clean, production-ready React code, cutting UI sprint development time by over 35%.',
    websiteUrl: 'https://copycat.dev',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['React UI', 'Pixel Perfect', 'Figma to Code'],
    additionalCategories: ['ai-figma-to-code']
  },
  {
    name: 'Visual Copilot by Builder.io',
    slug: 'visual-copilot',
    tagline: '1-click AI Figma to code converter for React, Vue, Svelte, Angular, and Qwik',
    description: 'Visual Copilot uses custom LLMs trained on millions of design components to compile Figma designs into clean, framework-agnostic frontend code.',
    websiteUrl: 'https://builder.io/m/design-to-code',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Builder.io', 'Figma to React', 'AI UI Compiler'],
    additionalCategories: ['ai-figma-to-code']
  },

  // 3. ai-sql-query-generators
  {
    name: 'SQLAI.ai',
    slug: 'sqlai-ai',
    tagline: 'Generate, optimize, and explain complex SQL queries using conversational AI',
    description: 'SQLAI connects to PostgreSQL, MySQL, Snowflake, and BigQuery, converting natural language into optimized SQL queries with instant query plan analysis.',
    websiteUrl: 'https://sqlai.ai',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['SQL Generator', 'Query Optimizer', 'PostgreSQL'],
    additionalCategories: ['ai-sql-query-generators']
  },
  {
    name: 'SeekWell',
    slug: 'seekwell',
    tagline: 'Query SQL databases using plain English and automate reporting syncs',
    description: 'SeekWell allows non-technical business teams to query enterprise databases in natural language and automatically push query results into Google Sheets and Slack.',
    websiteUrl: 'https://seekwell.io',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Text to SQL', 'Database Sync', 'Business Intelligence'],
    additionalCategories: ['ai-sql-query-generators']
  },
  {
    name: 'Defog.ai',
    slug: 'defog-ai',
    tagline: 'Fine-tuned enterprise text-to-SQL for Snowflake, Redshift, and Databricks',
    description: 'Defog delivers self-hosted and on-premise LLMs fine-tuned specifically for relational SQL queries, achieving 99%+ schema execution accuracy.',
    websiteUrl: 'https://defog.ai',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.9,
    verified: true,
    tags: ['Enterprise SQL', 'Data Warehouse', 'Self-Hosted LLM'],
    additionalCategories: ['ai-sql-query-generators']
  },
  {
    name: 'BlazeSQL',
    slug: 'blazesql',
    tagline: 'AI SQL assistant and data analyst for desktop and web database workflows',
    description: 'BlazeSQL connects securely to private databases, generating SQL queries, answering ad-hoc data questions, and creating interactive metric charts.',
    websiteUrl: 'https://blazesql.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Desktop SQL', 'Data Analytics', 'Query Assistant'],
    additionalCategories: ['ai-sql-query-generators']
  },
  {
    name: 'EverSQL',
    slug: 'eversql',
    tagline: 'Automatic SQL query optimizer and indexing recommendation platform',
    description: 'EverSQL rewrites slow database queries and provides automated index recommendations to speed up MySQL, PostgreSQL, and MariaDB instances.',
    websiteUrl: 'https://eversql.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Query Tuning', 'Database Indexing', 'Performance Optimizer'],
    additionalCategories: ['ai-sql-query-generators']
  },

  // 4. ai-automated-test-generators
  {
    name: 'Mabl AI',
    slug: 'mabl-ai',
    tagline: 'Intelligent test automation platform for continuous web, mobile, and API testing',
    description: 'Mabl integrates AI into the QA pipeline to auto-heal broken tests, monitor application performance, and validate end-to-end user journeys.',
    websiteUrl: 'https://mabl.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['E2E Testing', 'Auto-Healing', 'QA Automation'],
    additionalCategories: ['ai-automated-test-generators']
  },
  {
    name: 'Testsigma',
    slug: 'testsigma-ai',
    tagline: 'GenAI-powered test automation platform for web, mobile apps, and APIs',
    description: 'Testsigma lets engineering teams write automated tests in plain English with self-healing AI capabilities and parallel cloud execution across 3,000+ browsers.',
    websiteUrl: 'https://testsigma.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Low-Code QA', 'Cross-Browser', 'Plain English Tests'],
    additionalCategories: ['ai-automated-test-generators']
  },
  {
    name: 'Applitools Eyes',
    slug: 'applitools-eyes',
    tagline: 'Visual AI testing and automated UI validation across all screen resolutions',
    description: 'Applitools Visual AI emulates the human eye to detect visual bugs, layout shifts, and functional regressions across every browser, OS, and mobile device.',
    websiteUrl: 'https://applitools.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Visual Regression', 'UI Testing', 'Visual AI'],
    additionalCategories: ['ai-automated-test-generators']
  },
  {
    name: 'Functionize',
    slug: 'functionize-ai',
    tagline: 'Autonomous enterprise testing platform powered by deep learning and computer vision',
    description: 'Functionize builds resilient end-to-end tests from natural language requirements and updates selectors dynamically as your UI evolves.',
    websiteUrl: 'https://functionize.com',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.7,
    verified: true,
    tags: ['Autonomous QA', 'Computer Vision', 'Enterprise Testing'],
    additionalCategories: ['ai-automated-test-generators']
  },
  {
    name: 'Roost.ai',
    slug: 'roost-ai',
    tagline: 'AI-generated unit, integration, and API test suites for source code repositories',
    description: 'Roost.ai scans your GitHub or GitLab repository to automatically generate unit tests, mocks, and integration test suites that increase code coverage.',
    websiteUrl: 'https://roost.ai',
    category: 'Coding Assistants',
    category_id: 'c5',
    categoryName: 'Coding Assistants',
    categorySlug: 'coding-assistants',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Unit Test AI', 'API Tests', 'Code Coverage'],
    additionalCategories: ['ai-automated-test-generators']
  },

  // 5. ai-cold-email-outreach
  {
    name: 'Saleshandy',
    slug: 'saleshandy',
    tagline: 'Cold email outreach platform with automated email warmup and multi-inbox rotation',
    description: 'Saleshandy allows sales teams to send personalized cold email sequences at scale with automated mailbox rotation, A/B testing, and deliverability tracking.',
    websiteUrl: 'https://saleshandy.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Cold Email', 'Inbox Warmup', 'Sales Sequences'],
    additionalCategories: ['ai-cold-email-outreach']
  },
  {
    name: 'Woodpecker',
    slug: 'woodpecker-co',
    tagline: 'Cold email and lead generation tool engineered for deliverability and agencies',
    description: 'Woodpecker automates personalized sales follow-ups, checks domain health in real time, and prevents spam folder landings with smart sending algorithms.',
    websiteUrl: 'https://woodpecker.co',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Email Deliverability', 'Agency Outreach', 'Lead Generation'],
    additionalCategories: ['ai-cold-email-outreach']
  },

  // 6. ai-autonomous-sdrs
  {
    name: 'Bounti AI',
    slug: 'bounti-ai',
    tagline: 'Autonomous AI SDR mapping account research and executing personalized outbound plays',
    description: 'Bounti conducts deep company research, reads financial filings, and crafts hyper-personalized account narratives to book meetings for enterprise sales teams.',
    websiteUrl: 'https://bounti.ai',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Autonomous SDR', 'Account Research', 'Enterprise Outbound'],
    additionalCategories: ['ai-autonomous-sdrs']
  },
  {
    name: 'Outbound AI',
    slug: 'outbound-ai',
    tagline: 'Autonomous conversational SDR agents managing end-to-end outbound pipelines',
    description: 'Outbound AI deploys specialized AI agents that identify intent signals, verify prospect data, and conduct conversational email outreach.',
    websiteUrl: 'https://outbound.ai',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.7,
    verified: true,
    tags: ['AI Sales Agent', 'Outbound Pipeline', 'Conversational SDR'],
    additionalCategories: ['ai-autonomous-sdrs']
  },
  {
    name: 'Reply.io Jason AI',
    slug: 'reply-io-jason',
    tagline: 'B2B sales assistant and conversational AI SDR powered by ChatGPT',
    description: 'Jason AI creates multichannel outreach sequences, handles prospect objections over email, and automatically books meetings directly on your calendar.',
    websiteUrl: 'https://reply.io',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Jason AI', 'Multichannel Sales', 'Meeting Booking'],
    additionalCategories: ['ai-autonomous-sdrs']
  },

  // 7. ai-ad-creative-generators
  {
    name: 'Revealbot',
    slug: 'revealbot',
    tagline: 'Automated digital ad management, optimization, and scaling for Meta, Google, and TikTok',
    description: 'Revealbot automates routine ad management tasks with conditional rules, creative auto-testing, and automated budget scaling across social ad networks.',
    websiteUrl: 'https://revealbot.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Ad Automation', 'Rule Engine', 'Performance Scaling'],
    additionalCategories: ['ai-ad-creative-generators']
  },
  {
    name: 'Marpipe',
    slug: 'marpipe',
    tagline: 'Multivariate creative testing platform for high-scale e-commerce paid social',
    description: 'Marpipe automates the creation and testing of hundreds of ad creative variations to discover the highest ROAS headlines, product backgrounds, and call-to-actions.',
    websiteUrl: 'https://marpipe.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Multivariate Testing', 'Ad Creatives', 'ROAS Optimization'],
    additionalCategories: ['ai-ad-creative-generators']
  },
  {
    name: 'Creatopy AI',
    slug: 'creatopy-ai',
    tagline: 'AI visual production and automated digital ad design platform for teams',
    description: 'Creatopy generates on-brand animated HTML5 and video banner ad sets across 40+ dimensions simultaneously with automated brand styling.',
    websiteUrl: 'https://creatopy.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Banner Ads', 'Ad Production', 'HTML5 Ads'],
    additionalCategories: ['ai-ad-creative-generators']
  },
  {
    name: 'Smartly.io',
    slug: 'smartly-io',
    tagline: 'AI-powered social advertising platform automating creative and campaign management',
    description: 'Smartly combines creative automation, dynamic product ads, and algorithmic bidding across Meta, Pinterest, Snap, and TikTok.',
    websiteUrl: 'https://smartly.io',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Social Advertising', 'Dynamic Ads', 'Enterprise Creative'],
    additionalCategories: ['ai-ad-creative-generators']
  },
  {
    name: 'AdScale',
    slug: 'adscale',
    tagline: 'AI e-commerce advertising platform automating Google, Facebook, and Instagram ads',
    description: 'AdScale connects directly to Shopify and WooCommerce stores, using machine learning to generate ad copy, build audiences, and optimize ad spend automatically.',
    websiteUrl: 'https://adscale.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['E-Commerce Ads', 'Shopify Ads', 'Automated PPC'],
    additionalCategories: ['ai-ad-creative-generators']
  },

  // 8. ai-landing-page-builders
  {
    name: 'Webflow AI',
    slug: 'webflow-ai',
    tagline: 'Visual development platform with generative AI styling, copy, and layout features',
    description: 'Webflow AI allows web designers to generate responsive page sections, rewrite conversion-focused copy, and translate entire sites inside Webflow Designer.',
    websiteUrl: 'https://webflow.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Visual Development', 'CMS', 'Landing Pages'],
    additionalCategories: ['ai-landing-page-builders']
  },
  {
    name: 'Instapage AI',
    slug: 'instapage-ai',
    tagline: 'Leader in landing page software with AI content generation and heatmaps',
    description: 'Instapage combines AI headline and copy generation with multivariate testing, server-side tracking, and 1:1 ad-to-page personalization.',
    websiteUrl: 'https://instapage.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Landing Page Optimization', 'PPC Landing Pages', 'Ad Personalization'],
    additionalCategories: ['ai-landing-page-builders']
  },
  {
    name: 'Landingi AI',
    slug: 'landingi-ai',
    tagline: 'No-code landing page platform with built-in AI copywriting and event tracking',
    description: 'Landingi enables marketing teams to build, publish, and optimize micro-sites and lead generation funnels with AI text generation and automated SEO.',
    websiteUrl: 'https://landingi.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Lead Funnels', 'No-Code Builder', 'Landing Page AI'],
    additionalCategories: ['ai-landing-page-builders']
  },
  {
    name: '60sec.site',
    slug: '60sec-site',
    tagline: 'Launch high-converting landing pages from simple ideas in sixty seconds',
    description: '60sec.site generates complete landing pages with pricing tiers, hero illustrations, feature breakdowns, and integrated payment links for startups.',
    websiteUrl: 'https://60sec.site',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Rapid Prototype', 'Startup Funnel', 'Instant Landing Page'],
    additionalCategories: ['ai-landing-page-builders']
  },
  {
    name: 'Sitekick',
    slug: 'sitekick-ai',
    tagline: 'AI landing page builder creating conversion-ready pages with 1-click copywriting',
    description: 'Sitekick builds stunning landing pages without coding, creating custom copy, imagery, and layout structure optimized for high conversion rates.',
    websiteUrl: 'https://sitekick.ai',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['No-Code Builder', 'Conversion Copy', 'Landing Page Studio'],
    additionalCategories: ['ai-landing-page-builders']
  },

  // 9. ai-brand-voice-governance
  {
    name: 'Acrolinx',
    slug: 'acrolinx',
    tagline: 'Enterprise content governance and AI brand alignment platform',
    description: 'Acrolinx acts as an automated editorial gatekeeper, ensuring all global marketing copy complies with corporate brand tone, clarity, and terminology.',
    websiteUrl: 'https://acrolinx.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Content Governance', 'Brand Voice', 'Style Guide Compliance'],
    additionalCategories: ['ai-brand-voice-governance']
  },
  {
    name: 'Contentful AI',
    slug: 'contentful-ai',
    tagline: 'Composable content platform with built-in AI translation and voice governance',
    description: 'Contentful AI accelerates omnichannel content creation by providing real-time brand tone adjustments, SEO suggestions, and localized copy variants.',
    websiteUrl: 'https://contentful.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Composable CMS', 'Enterprise Governance', 'Brand Localization'],
    additionalCategories: ['ai-brand-voice-governance']
  },
  {
    name: 'Frontify Brand Assistant',
    slug: 'frontify-ai',
    tagline: 'All-in-one brand management platform with AI style guide copilot',
    description: 'Frontify empowers marketing teams to enforce visual and written brand identity guidelines across digital asset management and marketing campaigns.',
    websiteUrl: 'https://frontify.com',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Brand Guidelines', 'Asset Management', 'Voice Consistency'],
    additionalCategories: ['ai-brand-voice-governance']
  },
  {
    name: 'Grammarly Business',
    slug: 'grammarly-business',
    tagline: 'AI communication assistant ensuring brand tone consistency across company emails and docs',
    description: 'Grammarly Business equips teams with custom company style guides, brand tone profiles, and snippets that keep communication consistent across all apps.',
    websiteUrl: 'https://grammarly.com/business',
    category: 'Marketing & Sales',
    category_id: 'c6',
    categoryName: 'Marketing & Sales',
    categorySlug: 'marketing-sales',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.9,
    verified: true,
    tags: ['Team Tone', 'Style Guides', 'Brand Consistency'],
    additionalCategories: ['ai-brand-voice-governance']
  },

  // 10. ai-calendar-scheduling
  {
    name: 'Cal.com AI',
    slug: 'cal-com-ai',
    tagline: 'Open-source scheduling infrastructure with AI booking routing and assistants',
    description: 'Cal.com offers customizable scheduling links with AI routing forms that qualify inbound leads and schedule meetings with the appropriate team member.',
    websiteUrl: 'https://cal.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Open Source', 'Scheduling Link', 'AI Routing'],
    additionalCategories: ['ai-calendar-scheduling']
  },
  {
    name: 'Vimcal',
    slug: 'vimcal',
    tagline: 'The world fastest calendar designed for remote workers with AI timezone translation',
    description: 'Vimcal gives professionals keyboard shortcuts, instant slot sharing, and AI timezone conversion to schedule international calls in seconds.',
    websiteUrl: 'https://vimcal.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Fast Calendar', 'Timezone Converter', 'Remote Work'],
    additionalCategories: ['ai-calendar-scheduling']
  },
  {
    name: 'Mayday',
    slug: 'mayday-ai',
    tagline: 'AI-assisted calendar and scheduling app that protects your focus time and priorities',
    description: 'Mayday learns your work rhythms to schedule meetings at optimal times, automatically blocking deep work sessions and buffer periods between calls.',
    websiteUrl: 'https://mayday.am',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Focus Time', 'Smart Calendar', 'Deep Work'],
    additionalCategories: ['ai-calendar-scheduling']
  },

  // 11. ai-note-taking-knowledge
  {
    name: 'Roam Research',
    slug: 'roam-research',
    tagline: 'A note-taking tool for networked thought and bidirectional knowledge graphing',
    description: 'Roam Research organizes notes as a dynamic graph database, connecting thoughts, citations, and daily logs with bidirectional links and query blocks.',
    websiteUrl: 'https://roamresearch.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Networked Thought', 'Knowledge Graph', 'PKM'],
    additionalCategories: ['ai-note-taking-knowledge']
  },
  {
    name: 'Reflect AI',
    slug: 'reflect-ai',
    tagline: 'Mirrored note-taking with AI whisper transcription and connected thoughts',
    description: 'Reflect syncs daily notes, meetings, and ideas with end-to-end encryption, utilizing integrated AI to transcribe voice memos and summarize meeting minutes.',
    websiteUrl: 'https://reflect.app',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Audio Notes', 'Encrypted PKM', 'Second Brain'],
    additionalCategories: ['ai-note-taking-knowledge']
  },

  // 12. ai-email-productivity
  {
    name: 'Spark Mail AI',
    slug: 'spark-mail-ai',
    tagline: 'Smart email client featuring AI composition, fast summaries, and smart inbox triage',
    description: 'Spark organizes personal and team inboxes into prioritized categories, offering 1-click AI replies, tone adjusters, and thread summaries.',
    websiteUrl: 'https://sparkmailapp.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Smart Inbox', 'Email Summary', 'Quick Reply'],
    additionalCategories: ['ai-email-productivity']
  },
  {
    name: 'Clean Email',
    slug: 'clean-email',
    tagline: 'Automated inbox cleaner that organizes newsletters and unsubscribes from spam',
    description: 'Clean Email uses smart view algorithms to bundle promotional emails, automate archiving rules, and keep mailboxes clutter-free with privacy protection.',
    websiteUrl: 'https://clean.email',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Inbox Cleaner', 'Unsubscribe', 'Email Organization'],
    additionalCategories: ['ai-email-productivity']
  },
  {
    name: 'Spike AI',
    slug: 'spike-ai',
    tagline: 'Conversational email and unified team workspace turning messy threads into chats',
    description: 'Spike transforms standard email into interactive chat threads, integrating AI writing assistance, collaborative docs, and team voice calls in one app.',
    websiteUrl: 'https://spikenow.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Conversational Email', 'Team Chat', 'Inbox Zero'],
    additionalCategories: ['ai-email-productivity']
  },
  {
    name: 'Canary Mail AI',
    slug: 'canary-mail-ai',
    tagline: 'Secure email client with AI Copilot for drafting emails and highlighting critical action items',
    description: 'Canary Mail provides end-to-end encrypted messaging paired with an intelligent Copilot that drafts contextual replies and detects urgent messages.',
    websiteUrl: 'https://canarymail.io',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Encrypted Email', 'Copilot Email', 'Action Items'],
    additionalCategories: ['ai-email-productivity']
  },
  {
    name: 'Missive AI',
    slug: 'missive-ai',
    tagline: 'Collaborative team inbox with shared drafts and OpenAI-powered email writing',
    description: 'Missive allows customer support and sales teams to manage email, SMS, and WhatsApp conversations collaboratively with shared AI writing prompts.',
    websiteUrl: 'https://missiveapp.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Shared Inbox', 'Team Collaboration', 'AI Drafting'],
    additionalCategories: ['ai-email-productivity']
  },

  // 13. ai-project-management
  {
    name: 'Taskade AI',
    slug: 'taskade-ai',
    tagline: 'AI agents, mind maps, and workflow automation for modern project management',
    description: 'Taskade combines task lists, mind mapping, and autonomous AI agents that draft project roadmaps, research tasks, and summarize team sprints.',
    websiteUrl: 'https://taskade.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Task Management', 'Mind Mapping', 'AI Workflow'],
    additionalCategories: ['ai-project-management']
  },
  {
    name: 'Jira Cloud AI',
    slug: 'jira-cloud-ai',
    tagline: 'Atlassian Intelligence powering agile sprint planning and issue breakdowns',
    description: 'Jira AI automatically generates user stories, translates natural language into Jira Query Language (JQL), and summarizes complex ticket histories.',
    websiteUrl: 'https://atlassian.com/software/jira',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Agile Sprints', 'Jira AI', 'Issue Tracking'],
    additionalCategories: ['ai-project-management']
  },
  {
    name: 'Hive AI',
    slug: 'hive-ai',
    tagline: 'Project management platform with automated action item extraction and timeline prediction',
    description: 'Hive uses AI to transcribe meeting notes into actionable project tasks, assign subtasks to teammates, and predict project completion timelines.',
    websiteUrl: 'https://hive.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Project Tracking', 'Action Items', 'Team Timelines'],
    additionalCategories: ['ai-project-management']
  },
  {
    name: 'Notion Projects AI',
    slug: 'notion-projects-ai',
    tagline: 'Integrated project management with AI autofill, sprint boards, and task summaries',
    description: 'Notion Projects provides flexible kanban boards, Gantt timelines, and AI properties that extract action items and summarize engineering status updates.',
    websiteUrl: 'https://notion.so/product/projects',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Sprint Boards', 'Kanban AI', 'Task Summaries'],
    additionalCategories: ['ai-project-management']
  },

  // 14. ai-document-readers-summarizers
  {
    name: 'AskYourPDF',
    slug: 'askyourpdf',
    tagline: 'Chat with any PDF document and extract citations with conversational AI',
    description: 'AskYourPDF transforms dry PDF documents into interactive conversations, providing accurate answers with highlighted page citations across research papers and contracts.',
    websiteUrl: 'https://askyourpdf.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Chat with PDF', 'Citation Search', 'Document Copilot'],
    additionalCategories: ['ai-document-readers-summarizers']
  },
  {
    name: 'PDF.ai',
    slug: 'pdf-ai',
    tagline: 'Chat with documents, legal agreements, financial reports, and study guides',
    description: 'PDF.ai lets users upload any document to ask questions, extract key terms, and generate executive summaries with direct source verification.',
    websiteUrl: 'https://pdf.ai',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['PDF Analysis', 'Contract Review', 'Document Q&A'],
    additionalCategories: ['ai-document-readers-summarizers']
  },
  {
    name: 'LightPDF AI',
    slug: 'lightpdf-ai',
    tagline: 'AI PDF analyzer, converter, and summarizer with multi-document comparison',
    description: 'LightPDF analyzes lengthy PDFs, Word documents, and spreadsheets, generating concise summaries and allowing cross-document querying in seconds.',
    websiteUrl: 'https://lightpdf.com',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Document Compare', 'PDF Summary', 'Table Extraction'],
    additionalCategories: ['ai-document-readers-summarizers']
  },
  {
    name: 'Lateral AI',
    slug: 'lateral-ai',
    tagline: 'Document reading tool for researchers comparing concepts across multiple papers',
    description: 'Lateral AI organizes large document collections into an intuitive comparative matrix, highlighting key findings and methodology across dozens of PDFs at once.',
    websiteUrl: 'https://lateral.io',
    category: 'Productivity',
    category_id: 'c7',
    categoryName: 'Productivity',
    categorySlug: 'productivity',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Comparative Reading', 'Research Synthesis', 'Document Matrix'],
    additionalCategories: ['ai-document-readers-summarizers']
  }
];

let added = 0;
let updated = 0;
const existingSlugs = new Map<string, any>();
tools.forEach(t => existingSlugs.set((t.slug || '').toLowerCase(), t));

for (const seed of batch2Tools) {
  const slug = seed.slug.toLowerCase();
  if (!existingSlugs.has(slug)) {
    const newTool = {
      ...seed,
      id: `tool-${seed.slug}`,
      status: 'Published'
    };
    tools.push(newTool);
    existingSlugs.set(slug, newTool);
    added++;
  } else {
    const existing = existingSlugs.get(slug);
    existing.additionalCategories = existing.additionalCategories || [];
    seed.additionalCategories.forEach(ac => {
      if (!existing.additionalCategories.includes(ac)) {
        existing.additionalCategories.push(ac);
      }
    });
    updated++;
  }
}

fs.writeFileSync(toolsJsonPath, JSON.stringify(tools, null, 2), 'utf8');
console.log(`✓ Batch 2 completed! Added: ${added}, Updated: ${updated}`);
