import fs from 'fs';
import path from 'path';

const projectDir = process.cwd();
const toolsJsonPath = path.join(projectDir, 'data', 'tools.json');

const tools: any[] = JSON.parse(fs.readFileSync(toolsJsonPath, 'utf8'));

// Batch 3 seed tools: Categories 7, 8, 9
const batch3Tools = [
  // 1. ai-podcast-editors
  {
    name: 'Sounder.fm',
    slug: 'sounder-fm',
    tagline: 'Audio intelligence platform for automated podcast transcription, SEO, and brand safety',
    description: 'Sounder provides audio publishers with contextual insights, automated chapter creation, keyword timestamps, and brand-safe ad placement technology.',
    websiteUrl: 'https://sounder.fm',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Podcast Intelligence', 'Chapter Timestamps', 'Brand Safety'],
    additionalCategories: ['ai-podcast-editors']
  },
  {
    name: 'Resound',
    slug: 'resound-fm',
    tagline: 'AI podcast editor that automatically detects and removes filler words and long silences',
    description: 'Resound is an AI audio engineer that listens to spoken recordings and automatically cuts out "ums", "ahs", and awkward gaps in seconds.',
    websiteUrl: 'https://resound.fm',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Filler Word Removal', 'Podcast Editor', 'Silence Trimmer'],
    additionalCategories: ['ai-podcast-editors']
  },

  // 2. ai-music-song-generators
  {
    name: 'Boomy AI',
    slug: 'boomy-ai',
    tagline: 'Make original songs in seconds and submit them directly to streaming platforms',
    description: 'Boomy enables anyone without musical training to compose, arrange, and produce original tracks with custom lead vocals and genre soundsets.',
    websiteUrl: 'https://boomy.com',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['AI Music', 'Song Generator', 'Streaming Distribution'],
    additionalCategories: ['ai-music-song-generators']
  },
  {
    name: 'Loudly',
    slug: 'loudly-ai',
    tagline: 'AI music generator and massive royalty-free audio library for creators',
    description: 'Loudly generates customizable studio-quality music tracks from genre prompts, instruments, and energy levels for films, games, and advertisements.',
    websiteUrl: 'https://loudly.com',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Royalty Free Music', 'Track Producer', 'Background Music'],
    additionalCategories: ['ai-music-song-generators']
  },
  {
    name: 'AIVA',
    slug: 'aiva-ai',
    tagline: 'Artificial intelligence composing emotional soundtrack music for film and gaming',
    description: 'AIVA (Artificial Intelligence Virtual Artist) composes symphonic and cinematic musical scores with exportable MIDI and full copyright ownership.',
    websiteUrl: 'https://aiva.ai',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Cinematic Scores', 'MIDI Generation', 'Classical AI'],
    additionalCategories: ['ai-music-song-generators']
  },
  {
    name: 'Soundful',
    slug: 'soundful-ai',
    tagline: 'Studio-grade royalty-free music generator for producers, brands, and creators',
    description: 'Soundful uses proprietary algorithmic generation to build unique musical stems, loops, and master tracks across EDM, Hip Hop, and Pop.',
    websiteUrl: 'https://soundful.com',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Audio Stems', 'Beat Maker', 'Music Production'],
    additionalCategories: ['ai-music-song-generators']
  },
  {
    name: 'Splash Pro',
    slug: 'splash-pro',
    tagline: 'Generative text-to-music platform creating vocals, beats, and instruments',
    description: 'Splash Pro turns descriptive natural language into full musical arrangements, incorporating synthetic singing voices, rap verses, and energetic drums.',
    websiteUrl: 'https://splashpro.ai',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Text to Music', 'AI Vocals', 'Beat Production'],
    additionalCategories: ['ai-music-song-generators']
  },

  // 3. ai-audio-noise-removers
  {
    name: 'Superpowered CrispyMic',
    slug: 'crispymic-ai',
    tagline: 'Real-time microphone audio cleaner removing background noise and room reverberation',
    description: 'CrispyMic is a virtual microphone driver that cleans up voice chat on Discord, Zoom, and Google Meet with zero perceptible audio latency.',
    websiteUrl: 'https://crispymic.com',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Microphone Noise', 'Low Latency', 'Voice Isolation'],
    additionalCategories: ['ai-audio-noise-removers']
  },
  {
    name: 'Accentize VoiceGate',
    slug: 'accentize-voicegate',
    tagline: 'Machine learning noise reduction plug-in for professional audio engineers',
    description: 'VoiceGate is a VST/AU audio plug-in that removes ambient street noise, air conditioning hum, and unwanted room reflections from dialogue recordings.',
    websiteUrl: 'https://accentize.com/voicegate',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Audio Plug-in', 'Dialogue Clean', 'Studio Noise Gate'],
    additionalCategories: ['ai-audio-noise-removers']
  },
  {
    name: 'Moises.ai',
    slug: 'moises-ai',
    tagline: 'AI audio separation, vocal remover, and stem isolation studio for musicians',
    description: 'Moises isolates individual vocal tracks, drums, bass, and instruments from any recorded song while stripping background hiss and ambient bleed.',
    websiteUrl: 'https://moises.ai',
    category: 'Audio & Voice',
    category_id: 'c4',
    categoryName: 'Audio & Voice',
    categorySlug: 'audio-voice',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Stem Separation', 'Vocal Remover', 'Noise Cleaner'],
    additionalCategories: ['ai-audio-noise-removers']
  },

  // 4. ai-customer-support-bots
  {
    name: 'Zendesk AI',
    slug: 'zendesk-ai',
    tagline: 'Intelligent triage, customer support bots, and agent copilot built into Zendesk',
    description: 'Zendesk AI automates ticket classification, resolves common customer requests autonomously, and guides agents with context-aware response suggestions.',
    websiteUrl: 'https://zendesk.com/service/ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.9,
    verified: true,
    tags: ['Help Desk', 'Customer Support', 'Ticket Triage'],
    additionalCategories: ['ai-customer-support-bots']
  },
  {
    name: 'Freshchat Freddy AI',
    slug: 'freshchat-freddy-ai',
    tagline: 'Autonomous customer support agent and self-service bots across web and mobile',
    description: 'Freddy AI resolves routine inquiries across WhatsApp, web chat, and email, handing complex issues to human agents with summarized ticket context.',
    websiteUrl: 'https://freshworks.com/freshchat',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Freddy AI', 'Omnichannel Support', 'Customer Chatbot'],
    additionalCategories: ['ai-customer-support-bots']
  },
  {
    name: 'Decagon',
    slug: 'decagon-ai',
    tagline: 'Enterprise customer support AI agents handling complex transactions autonomously',
    description: 'Decagon builds generative AI support agents that integrate into internal databases to issue refunds, update orders, and resolve customer issues end-to-end.',
    websiteUrl: 'https://decagon.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.9,
    verified: true,
    tags: ['Autonomous Support', 'Enterprise AI', 'Action Execution'],
    additionalCategories: ['ai-customer-support-bots']
  },
  {
    name: 'Maven AGI',
    slug: 'maven-agi',
    tagline: 'Generative AI platform delivering autonomous support and agent assistance',
    description: 'Maven AGI resolves up to 93% of customer inquiries without human intervention while providing human agents with instantaneous knowledge retrieval.',
    websiteUrl: 'https://mavenagi.com',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Autonomous Resolution', 'Agent Copilot', 'Customer Service'],
    additionalCategories: ['ai-customer-support-bots']
  },
  {
    name: 'Ultimate.ai',
    slug: 'ultimate-ai',
    tagline: 'Enterprise virtual customer service agents delivering multilingual support',
    description: 'Ultimate connects to leading CRMs, resolving customer support tickets in 100+ languages across chat, email, and social messaging channels.',
    websiteUrl: 'https://ultimate.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Multilingual Support', 'Zendesk Partner', 'Enterprise Chatbot'],
    additionalCategories: ['ai-customer-support-bots']
  },

  // 5. ai-internal-knowledge-bots
  {
    name: 'Guru AI',
    slug: 'guru-ai',
    tagline: 'AI enterprise search and wiki delivering verified internal knowledge anywhere',
    description: 'Guru indexes Slack, Google Drive, Jira, and company docs, delivering accurate, permission-controlled answers directly inside your daily workflow.',
    websiteUrl: 'https://getguru.com',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Enterprise Search', 'Company Wiki', 'Knowledge Base'],
    additionalCategories: ['ai-internal-knowledge-bots']
  },
  {
    name: 'Dust',
    slug: 'dust-tt',
    tagline: 'Custom AI assistants connected to company knowledge and daily business data',
    description: 'Dust connects modern LLMs with Notion, Google Drive, Slack, and GitHub, allowing teams to build custom conversational internal assistants in minutes.',
    websiteUrl: 'https://dust.tt',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Internal Assistants', 'Connected LLM', 'Notion Integration'],
    additionalCategories: ['ai-internal-knowledge-bots']
  },
  {
    name: 'Moveworks',
    slug: 'moveworks-ai',
    tagline: 'Generative AI platform for enterprise IT, HR, and employee workplace support',
    description: 'Moveworks uses conversational AI to resolve employee IT issues, grant software permissions, reset passwords, and answer policy questions instantly.',
    websiteUrl: 'https://moveworks.com',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.9,
    verified: true,
    tags: ['Workplace AI', 'IT Service Desk', 'Employee Support'],
    additionalCategories: ['ai-internal-knowledge-bots']
  },

  // 6. ai-whatsapp-omnichannel-bots
  {
    name: 'WATI',
    slug: 'wati-io',
    tagline: 'Official WhatsApp Business API platform for customer engagement and AI chatbots',
    description: 'WATI empowers businesses to build automated WhatsApp broadcast campaigns, customer support bots, and team inboxes with no-code chatbot flows.',
    websiteUrl: 'https://wati.io',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['WhatsApp Business', 'Chatbot Builder', 'Broadcast Automation'],
    additionalCategories: ['ai-whatsapp-omnichannel-bots']
  },
  {
    name: 'Respond.io AI',
    slug: 'respond-io',
    tagline: 'Customer conversation management platform for WhatsApp, Telegram, and Messenger',
    description: 'Respond.io centralizes messaging apps into a collaborative inbox, utilizing AI agents to route inquiries, respond to FAQs, and track sales conversations.',
    websiteUrl: 'https://respond.io',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Omnichannel Inbox', 'WhatsApp CRM', 'Messaging Automation'],
    additionalCategories: ['ai-whatsapp-omnichannel-bots']
  },

  // 7. ai-character-roleplay-chat
  {
    name: 'Janitor AI',
    slug: 'janitor-ai',
    tagline: 'Immersive character chat and roleplay platform with deep conversational memory',
    description: 'Janitor AI allows creators to converse with community-designed fictional characters across fantasy, sci-fi, and gaming worlds with custom LLM backends.',
    websiteUrl: 'https://janitorai.com',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Character Chat', 'Roleplay AI', 'Fictional Personas'],
    additionalCategories: ['ai-character-roleplay-chat']
  },
  {
    name: 'SpicyChat AI',
    slug: 'spicychat-ai',
    tagline: 'Dynamic conversational AI chatbot platform with thousands of unique personas',
    description: 'SpicyChat enables interactive storytelling, character interactions, and immersive dialogue with memory persistence and custom persona builders.',
    websiteUrl: 'https://spicychat.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Chatbot Personas', 'Creative Dialogue', 'Roleplay Stories'],
    additionalCategories: ['ai-character-roleplay-chat']
  },
  {
    name: 'Kindroid',
    slug: 'kindroid-ai',
    tagline: 'Ultra-realistic humanlike digital companion with dynamic voice and visual selfies',
    description: 'Kindroid builds customizable virtual companions capable of complex emotional reasoning, vocal phone calls, and realistic self-generated photography.',
    websiteUrl: 'https://kindroid.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Digital Companion', 'Virtual Friend', 'Voice Chatbot'],
    additionalCategories: ['ai-character-roleplay-chat']
  },
  {
    name: 'Moemate',
    slug: 'moemate-ai',
    tagline: 'Highly customizable AI companions with 2D/3D avatars and screen perception',
    description: 'Moemate brings virtual companions to life on your desktop, capable of voice conversations, reacting to your screen, and interacting in VR/3D environments.',
    websiteUrl: 'https://moemate.io',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['3D Companions', 'Screen Perception', 'Virtual Avatars'],
    additionalCategories: ['ai-character-roleplay-chat']
  },
  {
    name: 'CrushOn.AI',
    slug: 'crushon-ai',
    tagline: 'Conversational AI companion platform featuring diverse characters and roleplays',
    description: 'CrushOn offers rich roleplay environments where users can explore customized story scenarios, anime characters, and engaging dialogue simulations.',
    websiteUrl: 'https://crushon.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Interactive Fiction', 'Anime Chatbot', 'Roleplay Companion'],
    additionalCategories: ['ai-character-roleplay-chat']
  },

  // 8. ai-voice-receptionists
  {
    name: 'Phonely',
    slug: 'phonely-ai',
    tagline: 'AI phone answering receptionist for clinics, legal offices, and small businesses',
    description: 'Phonely answers inbound phone calls 24/7 with human-like conversation, booking client appointments and taking detailed caller notes.',
    websiteUrl: 'https://phonely.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Phone Receptionist', 'Appointment Booking', 'Virtual Assistant'],
    additionalCategories: ['ai-voice-receptionists']
  },
  {
    name: 'Goodcall',
    slug: 'goodcall-ai',
    tagline: 'Conversational AI phone assistant engineered specifically for local businesses',
    description: 'Goodcall answers incoming business calls instantly, providing caller hours, booking reservations, answering FAQs, and eliminating missed calls.',
    websiteUrl: 'https://goodcall.com',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Local Business', 'Call Answering', 'Inbound Reception'],
    additionalCategories: ['ai-voice-receptionists']
  },
  {
    name: 'Dialpad Ai',
    slug: 'dialpad-ai',
    tagline: 'Unified business communications with real-time call transcription and virtual reception',
    description: 'Dialpad Ai transcribes business calls in real-time, automates IVR call routing, and provides live coaching cards during customer conversations.',
    websiteUrl: 'https://dialpad.com',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Cloud PBX', 'Call Transcription', 'AI Reception'],
    additionalCategories: ['ai-voice-receptionists']
  },
  {
    name: 'Smith.ai',
    slug: 'smith-ai',
    tagline: '24/7 AI-backed virtual receptionists for business phone calls, web chat, and lead intake',
    description: 'Smith.ai screens inbound callers, collects payments, schedules consultations, and integrates call logs directly into your CRM.',
    websiteUrl: 'https://smith.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.9,
    verified: true,
    tags: ['Virtual Receptionist', 'Lead Intake', 'Answering Service'],
    additionalCategories: ['ai-voice-receptionists']
  },
  {
    name: 'PolyAI',
    slug: 'poly-ai',
    tagline: 'Enterprise conversational voice assistants that sound natural and resolve phone inquiries',
    description: 'PolyAI builds voice assistants for global banks, hotels, and telecom operators, handling complex caller verifications and transactions over the phone.',
    websiteUrl: 'https://poly.ai',
    category: 'AI Chatbots',
    category_id: 'b9c74436-f00a-41e0-aee9-6ab15d90d3ec',
    categoryName: 'AI Chatbots',
    categorySlug: 'ai-chatbots',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.9,
    verified: true,
    tags: ['Enterprise Voice', 'Contact Center', 'Conversational IVR'],
    additionalCategories: ['ai-voice-receptionists']
  },

  // 9. ai-browser-automation-agents
  {
    name: 'Stagehand',
    slug: 'stagehand-dev',
    tagline: 'Playwright-compatible AI browser automation SDK built for reliable web agents',
    description: 'Stagehand enables developers to write resilient browser automation with 3 simple primitives: act, extract, and observe, powered by modern LLMs.',
    websiteUrl: 'https://stagehand.dev',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.9,
    verified: true,
    tags: ['Browser SDK', 'Playwright AI', 'Web Agents'],
    additionalCategories: ['ai-browser-automation-agents']
  },
  {
    name: 'Induced AI',
    slug: 'induced-ai',
    tagline: 'Autonomous cloud browser agents automating complex back-office workflows and RPA',
    description: 'Induced runs agentic browser infrastructure in the cloud, allowing businesses to execute non-API browser tasks, file downloads, and data entry automatically.',
    websiteUrl: 'https://induced.ai',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Cloud Browser', 'Back-Office RPA', 'Agentic Automation'],
    additionalCategories: ['ai-browser-automation-agents']
  },
  {
    name: 'Automa',
    slug: 'automa-site',
    tagline: 'Open-source browser extension for automating repetitive web workflows and clicks',
    description: 'Automa features a visual drag-and-drop block builder to automate browser navigation, scrape web pages, fill forms, and schedule background runs.',
    websiteUrl: 'https://automa.site',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.7,
    verified: true,
    tags: ['Browser Extension', 'No-Code RPA', 'Web Automation'],
    additionalCategories: ['ai-browser-automation-agents']
  },
  {
    name: 'Browserless AI',
    slug: 'browserless-ai',
    tagline: 'Headless Chrome browser cloud infrastructure built for web scraping and AI agents',
    description: 'Browserless provides dedicated cloud browser pools designed for headless automation, PDF rendering, automated screenshots, and LLM-guided web navigation.',
    websiteUrl: 'https://browserless.io',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Headless Chrome', 'Cloud Browser', 'Automation Pool'],
    additionalCategories: ['ai-browser-automation-agents']
  },

  // 10. ai-data-extraction-agents
  {
    name: 'Apify AI',
    slug: 'apify-ai',
    tagline: 'The leading web scraping, data extraction, and cloud RPA actor platform',
    description: 'Apify hosts thousands of pre-built web scrapers and actors that extract structured data from e-commerce stores, social media platforms, and search engines.',
    websiteUrl: 'https://apify.com',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Web Scraping', 'Cloud Actors', 'Data Extraction'],
    additionalCategories: ['ai-data-extraction-agents']
  },
  {
    name: 'Bright Data Scraping Browser',
    slug: 'bright-data-ai',
    tagline: 'Automated scraping browser with built-in CAPTCHA solving and proxy rotation',
    description: 'Bright Data Scraping Browser enables web crawlers to bypass bot detection, fingerprinting, and CAPTCHAs while extracting structured HTML and JSON.',
    websiteUrl: 'https://brightdata.com',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Proxy Network', 'CAPTCHA Bypass', 'Scraping Browser'],
    additionalCategories: ['ai-data-extraction-agents']
  },
  {
    name: 'Zyte AI',
    slug: 'zyte-ai',
    tagline: 'AI-driven web data extraction delivering clean structured product and article data',
    description: 'Zyte automatically parses e-commerce product catalogs, job postings, and news articles into structured JSON without writing manual CSS selectors.',
    websiteUrl: 'https://zyte.com',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Automated Extraction', 'Catalog Scraping', 'Structured Data'],
    additionalCategories: ['ai-data-extraction-agents']
  },
  {
    name: 'Oxylabs AI Scraper',
    slug: 'oxylabs-ai',
    tagline: 'AI-powered web scraper API with automated proxy management and parsing',
    description: 'Oxylabs provides high-throughput SERP, e-commerce, and real estate data extraction with automated JavaScript rendering and anti-blocking technology.',
    websiteUrl: 'https://oxylabs.io',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Scraper API', 'E-Commerce Data', 'Proxy Rotation'],
    additionalCategories: ['ai-data-extraction-agents']
  },
  {
    name: 'ParseHub AI',
    slug: 'parsehub-ai',
    tagline: 'Free visual desktop web scraper extracting data from JavaScript and AJAX sites',
    description: 'ParseHub extracts data from interactive websites, handling logins, dropdown menus, paginated tables, and infinite scrolling feeds with 1 click.',
    websiteUrl: 'https://parsehub.com',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Visual Scraper', 'Desktop Scraper', 'AJAX Extraction'],
    additionalCategories: ['ai-data-extraction-agents']
  },

  // 11. ai-workflow-automation-agents
  {
    name: 'n8n AI',
    slug: 'n8n-ai',
    tagline: 'Fair-code workflow automation platform with native AI agent nodes and LangChain tools',
    description: 'n8n enables technical teams to build self-hosted or cloud-hosted automation pipelines, connecting multi-modal LLMs to 400+ SaaS applications.',
    websiteUrl: 'https://n8n.io',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Fair-Code', 'Workflow Automation', 'Self-Hosted AI'],
    additionalCategories: ['ai-workflow-automation-agents']
  },
  {
    name: 'Zapier Central',
    slug: 'zapier-central',
    tagline: 'Experimental workspace for building autonomous AI bots connected to 6,000+ apps',
    description: 'Zapier Central allows users to teach AI bots behaviors and actions using natural language, triggering cross-application automation reliably.',
    websiteUrl: 'https://zapier.com/central',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Zapier AI', 'Bot Builder', 'App Integration'],
    additionalCategories: ['ai-workflow-automation-agents']
  },
  {
    name: 'Activepieces',
    slug: 'activepieces-ai',
    tagline: 'Open-source business automation platform with AI copilot and community pieces',
    description: 'Activepieces provides an open-source alternative to Zapier, allowing teams to build automated workflows with AI-assisted code pieces and zero vendor lock-in.',
    websiteUrl: 'https://activepieces.com',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Open Source Automation', 'No-Code Workflow', 'AI Copilot'],
    additionalCategories: ['ai-workflow-automation-agents']
  },
  {
    name: 'Relay.app',
    slug: 'relay-app',
    tagline: 'Collaborative workflow automation with integrated 1-click human-in-the-loop approvals',
    description: 'Relay combines AI summaries, automated data extraction, and seamless human approval checkpoints into beautiful team workflow automations.',
    websiteUrl: 'https://relay.app',
    category: 'AI Agents',
    category_id: 'ai-agents',
    categoryName: 'AI Agents',
    categorySlug: 'ai-agents',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Human in the Loop', 'Team Workflow', 'AI Approvals'],
    additionalCategories: ['ai-workflow-automation-agents']
  }
];

let added = 0;
let updated = 0;
const existingSlugs = new Map<string, any>();
tools.forEach(t => existingSlugs.set((t.slug || '').toLowerCase(), t));

for (const seed of batch3Tools) {
  const slug = seed.slug.toLowerCase();
  if (!existingSlugs.has(slug)) {
    const newTool = {
      ...seed,
      id: `tool-${seed.slug}`,
      status: 'Published'
    };
    tools.push(newTool);
    existingSlugs.set(slug, newTool);
    added++;
  } else {
    const existing = existingSlugs.get(slug);
    existing.additionalCategories = existing.additionalCategories || [];
    seed.additionalCategories.forEach(ac => {
      if (!existing.additionalCategories.includes(ac)) {
        existing.additionalCategories.push(ac);
      }
    });
    updated++;
  }
}

fs.writeFileSync(toolsJsonPath, JSON.stringify(tools, null, 2), 'utf8');
console.log(`✓ Batch 3 completed! Added: ${added}, Updated: ${updated}`);
