import fs from 'fs';
import path from 'path';

const projectDir = process.cwd();
const toolsJsonPath = path.join(projectDir, 'data', 'tools.json');
const categoriesJsonPath = path.join(projectDir, 'data', 'categories.json');

const tools: any[] = JSON.parse(fs.readFileSync(toolsJsonPath, 'utf8'));
const categories: any[] = JSON.parse(fs.readFileSync(categoriesJsonPath, 'utf8'));

// Batch 1 seed tools: Categories 1, 2, 3
const batch1Tools = [
  // 1. ai-humanizers-bypass
  {
    name: 'WriteHuman',
    slug: 'writehuman-ai',
    tagline: 'Bypass AI detectors and convert AI content to authentic human writing',
    description: 'WriteHuman rewrites machine-generated text into natural, nuanced prose engineered to defeat Turnitin, ZeroGPT, and Copyleaks without altering original arguments.',
    websiteUrl: 'https://writehuman.ai',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['AI Humanizer', 'Detector Bypass', 'Writing Assistant'],
    additionalCategories: ['ai-humanizers-bypass']
  },
  {
    name: 'Phrasly AI',
    slug: 'phrasly-ai',
    tagline: 'AI humanizer designed to bypass Turnitin and maintain natural human tone',
    description: 'Phrasly turns ChatGPT and Claude generated drafts into authentic human-grade prose with realistic grammatical cadence, grammar checks, and zero AI footprints.',
    websiteUrl: 'https://phrasly.ai',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['AI Humanizer', 'Academic Writing', 'Turnitin Bypass'],
    additionalCategories: ['ai-humanizers-bypass']
  },
  {
    name: 'StealthWriter',
    slug: 'stealthwriter-ai',
    tagline: 'Converts AI text into undetectable, human-written content guaranteed to bypass detection',
    description: 'StealthWriter leverages multi-engine transformation algorithms to strip syntactic AI patterns while preserving factual accuracy and context.',
    websiteUrl: 'https://stealthwriter.ai',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['AI Humanizer', 'Bypass Detectors', 'Content Rewriter'],
    additionalCategories: ['ai-humanizers-bypass']
  },
  {
    name: 'Humanize AI',
    slug: 'humanize-ai',
    tagline: 'Free online tool to humanize AI text into natural, emotional prose',
    description: 'Humanize AI refactors mechanical syntax into fluid, colloquial expressions that read naturally to human reviewers and evade algorithmic detection.',
    websiteUrl: 'https://humanizeai.pro',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.6,
    verified: true,
    tags: ['Free Humanizer', 'Paraphraser', 'Content Polish'],
    additionalCategories: ['ai-humanizers-bypass']
  },
  {
    name: 'GPTInf',
    slug: 'gptinf-ai',
    tagline: 'Bypass AI content detection with smart sentence diversity and vocabulary rephrasing',
    description: 'GPTInf is built specifically to outsmart detectors by varying perplexity and burstiness across paragraphs, providing instant humanized outputs.',
    websiteUrl: 'https://gptinf.com',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.6,
    verified: true,
    tags: ['Bypass AI', 'Perplexity', 'SEO Content'],
    additionalCategories: ['ai-humanizers-bypass']
  },

  // 2. ai-youtube-video-scripts
  {
    name: 'VidIQ AI',
    slug: 'vidiq-ai',
    tagline: 'YouTube growth platform with AI title, script, and hook generators',
    description: 'VidIQ AI provides creators with viral video ideation, full script generation, high-CTR thumbnail prompts, and real-time competitor keyword analytics.',
    websiteUrl: 'https://vidiq.com',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['YouTube Script', 'Video Ideation', 'Viral Hooks'],
    additionalCategories: ['ai-youtube-video-scripts']
  },
  {
    name: 'TubeBuddy AI',
    slug: 'tubebuddy-ai',
    tagline: 'Channel optimization suite with AI title, description, and script assistants',
    description: 'TubeBuddy integrates directly into YouTube Studio offering AI script generation, thumbnail A/B testing, and automated SEO title drafting.',
    websiteUrl: 'https://tubebuddy.com',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['YouTube Assistant', 'Scriptwriting', 'Video SEO'],
    additionalCategories: ['ai-youtube-video-scripts']
  },

  // 3. ai-grant-proposal-writers
  {
    name: 'ProposalGenie',
    slug: 'proposalgenie-ai',
    tagline: 'AI grant and bid proposal writer that drafts compliance-ready funding bids',
    description: 'ProposalGenie accelerates non-profit, research, and government grant applications by structuring compliant responses based on funding criteria.',
    websiteUrl: 'https://proposalgenie.ai',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Grant Proposal', 'Bid Writing', 'Non-profit Funding'],
    additionalCategories: ['ai-grant-proposal-writers']
  },
  {
    name: 'GrantAssistant',
    slug: 'grantassistant-ai',
    tagline: 'Intelligent grant drafting platform for universities, researchers, and NGOs',
    description: 'GrantAssistant synthesizes organizational project goals and institutional budgets into compelling grant narratives tailored to specific foundation guidelines.',
    websiteUrl: 'https://grantassistant.ai',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Grant Narrative', 'Academic Grants', 'Institutional Funding'],
    additionalCategories: ['ai-grant-proposal-writers']
  },
  {
    name: 'Submittable AI',
    slug: 'submittable-ai',
    tagline: 'Social impact platform with smart grant application management and drafting',
    description: 'Submittable connects grantmakers and applicants with AI-assisted review workflows, application polishers, and submission governance.',
    websiteUrl: 'https://submittable.com',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Grant Management', 'Enterprise Grants', 'Philanthropy'],
    additionalCategories: ['ai-grant-proposal-writers']
  },
  {
    name: 'Fundwriter.ai',
    slug: 'fundwriter-ai',
    tagline: 'AI copywriting tool engineered for non-profit fundraising appeals and grants',
    description: 'Fundwriter helps non-profit fundraisers generate grant letters of intent, donor appeals, impact reports, and sponsorship pitches in minutes.',
    websiteUrl: 'https://fundwriter.ai',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.6,
    verified: true,
    tags: ['Fundraising', 'Non-profit', 'Grant Appeals'],
    additionalCategories: ['ai-grant-proposal-writers']
  },
  {
    name: 'RFP360 AI',
    slug: 'rfp360-ai',
    tagline: 'End-to-end RFP and proposal automation software for procurement and grants',
    description: 'RFP360 streamlines bid management with knowledge library search, automated answer drafting, and collaborative team review workflows.',
    websiteUrl: 'https://rfp360.com',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.7,
    verified: true,
    tags: ['RFP Automation', 'Bid Proposals', 'Procurement'],
    additionalCategories: ['ai-grant-proposal-writers']
  },

  // 4. ai-novel-fiction-writers
  {
    name: 'Squibler AI',
    slug: 'squibler-ai',
    tagline: 'AI novel and screenplay writing software for authors and creative writers',
    description: 'Squibler provides novelists and screenwriters with smart character development, story expansion, chapter outlines, and complete book structuring.',
    websiteUrl: 'https://squibler.io',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Novel Writing', 'Screenplay', 'Fiction Assistant'],
    additionalCategories: ['ai-novel-fiction-writers']
  },
  {
    name: 'Fablecraft AI',
    slug: 'fablecraft-ai',
    tagline: 'Narrative design platform and tabletop fiction story generator',
    description: 'Fablecraft assists creative authors and tabletop storytellers in developing intricate lore, dialogue branches, and atmospheric fictional settings.',
    websiteUrl: 'https://fablecraft.app',
    category: 'AI Writing Tools',
    category_id: 'c1',
    categoryName: 'AI Writing Tools',
    categorySlug: 'ai-writing-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Worldbuilding', 'Fiction Story', 'Creative Writing'],
    additionalCategories: ['ai-novel-fiction-writers']
  },

  // 5. ai-product-photography
  {
    name: 'Booth.ai',
    slug: 'booth-ai',
    tagline: 'Generative AI for studio-quality commercial e-commerce product photos',
    description: 'Booth.ai replaces costly physical photoshoots by generating photorealistic commercial product imagery from simple descriptive text and reference shots.',
    websiteUrl: 'https://booth.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Product Photos', 'E-Commerce Staging', 'Commercial Photography'],
    additionalCategories: ['ai-product-photography']
  },
  {
    name: 'Claid.ai',
    slug: 'claid-ai',
    tagline: 'Automated product image enhancement and AI background generation for marketplaces',
    description: 'Claid.ai automatically corrects lighting, scales resolution, removes imperfections, and generates studio backgrounds for millions of product SKUs.',
    websiteUrl: 'https://claid.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Marketplace Imagery', 'Product Staging', 'E-Commerce AI'],
    additionalCategories: ['ai-product-photography']
  },
  {
    name: 'CreatorKit',
    slug: 'creatorkit',
    tagline: 'AI product photoshoot and marketing video generator for Shopify brands',
    description: 'CreatorKit turns plain product pictures into high-converting lifestyle studio scenes and social media video advertisements with 1 click.',
    websiteUrl: 'https://creatorkit.com',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Shopify Photos', 'Product Studio', 'E-Commerce Ads'],
    additionalCategories: ['ai-product-photography']
  },
  {
    name: 'Caspa AI',
    slug: 'caspa-ai',
    tagline: 'Create photorealistic product photos with human models and custom backgrounds',
    description: 'Caspa AI lets e-commerce merchants stage products with realistic virtual human models and customizable lifestyle environments without hiring photographers.',
    websiteUrl: 'https://caspa.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Virtual Models', 'Product Staging', 'Commercial Photos'],
    additionalCategories: ['ai-product-photography']
  },

  // 6. ai-headshot-generators
  {
    name: 'BetterPic',
    slug: 'betterpic-ai',
    tagline: 'Studio-grade 4K AI executive headshots in 45 minutes',
    description: 'BetterPic converts smartphone selfies into professional corporate portraits with tailored wardrobe, natural lighting, and studio backdrops.',
    websiteUrl: 'https://betterpic.io',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Executive Headshots', 'LinkedIn Profile', 'Portrait Studio'],
    additionalCategories: ['ai-headshot-generators']
  },
  {
    name: 'TryItOn AI',
    slug: 'tryiton-ai',
    tagline: 'Expressive professional AI headshots and studio portraits for teams and creators',
    description: 'TryItOn produces high-fashion, editorial, and LinkedIn headshots from user-submitted photos with human retouching add-on options.',
    websiteUrl: 'https://tryitonai.com',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Professional Headshots', 'Studio Lighting', 'Corporate Portraits'],
    additionalCategories: ['ai-headshot-generators']
  },
  {
    name: 'ProPhotos AI',
    slug: 'prophotos-ai',
    tagline: 'Photorealistic AI headshots for entrepreneurs, executives, and remote teams',
    description: 'ProPhotos transforms casual photos into polished business headshots suitable for resumes, speaking engagements, and company websites.',
    websiteUrl: 'https://prophotos.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Business Headshot', 'Resume Photo', 'Corporate Team'],
    additionalCategories: ['ai-headshot-generators']
  },
  {
    name: 'HeadshotsByAI',
    slug: 'headshotsbyai',
    tagline: 'Instant AI business headshots delivered with photorealistic accuracy',
    description: 'HeadshotsByAI uses proprietary diffusion models trained on executive portraits to generate boardroom-ready images in under two hours.',
    websiteUrl: 'https://headshotsbyai.com',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.6,
    verified: true,
    tags: ['AI Portrait', 'LinkedIn Headshot', 'Photo Studio'],
    additionalCategories: ['ai-headshot-generators']
  },
  {
    name: 'The Multiverse AI',
    slug: 'themultiverse-ai',
    tagline: 'The #1 AI headshot generator trusted by Forbes, Google, and McKinsey professionals',
    description: 'The Multiverse AI produces impeccably realistic, high-definition business portraits with nuanced hair, skin, and wardrobe details.',
    websiteUrl: 'https://themultiverse.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.9,
    verified: true,
    tags: ['Executive Portraits', 'Team Headshots', 'Corporate Identity'],
    additionalCategories: ['ai-headshot-generators']
  },

  // 7. ai-vector-svg-generators
  {
    name: 'SVGcode',
    slug: 'svgcode',
    tagline: 'Open-source progressive web app to convert raster images to clean SVG vectors',
    description: 'SVGcode uses Potrace to vectorize JPG and PNG files into clean, editable SVG code with full customization of thresholds, paths, and colors.',
    websiteUrl: 'https://svgco.de',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.7,
    verified: true,
    tags: ['SVG Vectorizer', 'Open Source', 'Vector Graphics'],
    additionalCategories: ['ai-vector-svg-generators']
  },
  {
    name: 'Magik SVG',
    slug: 'magik-svg',
    tagline: 'Text-to-vector AI generator creating scalable SVG assets from natural prompts',
    description: 'Magik SVG empowers graphic designers and web developers to create resolution-independent SVG vector graphics, icons, and illustrations directly from text.',
    websiteUrl: 'https://magiksvg.com',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['SVG Generator', 'Text to Vector', 'Scalable Illustration'],
    additionalCategories: ['ai-vector-svg-generators']
  },
  {
    name: 'VectorCraftr',
    slug: 'vectorcraftr',
    tagline: 'AI vector graphics platform for creating custom SVG icons and illustrations',
    description: 'VectorCraftr allows creators to generate multi-layer vector illustrations, app icons, and logos with crisp paths and exportable SVG code.',
    websiteUrl: 'https://vectorcraftr.com',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Vector Graphics', 'App Icons', 'SVG Export'],
    additionalCategories: ['ai-vector-svg-generators']
  },
  {
    name: 'VectorArt.ai',
    slug: 'vectorart-ai',
    tagline: 'Curated generative vector art library and on-demand SVG generator',
    description: 'VectorArt.ai generates bespoke vector scenes, characters, and UI decorative elements ready for web and print applications without pixelation.',
    websiteUrl: 'https://vectorart.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Generative Vector', 'SVG Art', 'Graphic Design'],
    additionalCategories: ['ai-vector-svg-generators']
  },
  {
    name: 'SVG AI',
    slug: 'svg-ai',
    tagline: 'Instant AI vector and SVG illustration maker for modern product design',
    description: 'SVG AI transforms concepts into high-precision SVG vectors, geometric shapes, and isometric illustrations optimized for web speed and UI systems.',
    websiteUrl: 'https://svgai.net',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['SVG Maker', 'UI Vectors', 'Design System'],
    additionalCategories: ['ai-vector-svg-generators']
  },
  {
    name: 'Vexels AI',
    slug: 'vexels-ai',
    tagline: 'Commercial vector graphics and print-on-demand SVG design generator',
    description: 'Vexels offers an expansive suite of commercial-ready vector artwork and AI tools for merchandise creators, designers, and agencies.',
    websiteUrl: 'https://vexels.com',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Commercial Vector', 'Print on Demand', 'Merch Design'],
    additionalCategories: ['ai-vector-svg-generators']
  },

  // 8. ai-image-upscalers
  {
    name: 'Remini AI',
    slug: 'remini-ai',
    tagline: 'World-renowned AI photo enhancer and facial restoration engine',
    description: 'Remini uses advanced neural network technology to restore blurry, low-resolution photos into stunning high-definition masterpieces with razor-sharp facial details.',
    websiteUrl: 'https://remini.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Photo Restorer', 'Facial Detail', 'AI Upscaler'],
    additionalCategories: ['ai-image-upscalers']
  },
  {
    name: 'Krea AI Upscaler',
    slug: 'krea-ai-upscaler',
    tagline: 'Generative super-resolution upscaler adding realistic textures and cinematic clarity',
    description: 'Krea AI Upscaler reimagines image enhancement by halluncinating realistic photographic textures, specular highlights, and 8K details onto small images.',
    websiteUrl: 'https://krea.ai',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Generative Upscale', '8K Resolution', 'Detail Enhancer'],
    additionalCategories: ['ai-image-upscalers']
  },
  {
    name: "Let's Enhance",
    slug: 'lets-enhance',
    tagline: 'Automated AI image upscaler and color correction for e-commerce and print',
    description: "Let's Enhance increases resolution up to 16x without quality loss, removing compression artifacts while restoring vibrant colors for professional printing.",
    websiteUrl: 'https://letsenhance.io',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Print Upscaler', '16x Upscale', 'Artifact Removal'],
    additionalCategories: ['ai-image-upscalers']
  },
  {
    name: 'Bigjpg',
    slug: 'bigjpg',
    tagline: 'Deep Convolutional Neural Networks (CNN) image upscaler for anime and illustrations',
    description: 'Bigjpg specializes in upscaling anime illustrations and digital artwork up to 16x with zero noise, jagged edges, or visual degradation.',
    websiteUrl: 'https://bigjpg.com',
    category: 'AI Image Generators',
    category_id: 'c2',
    categoryName: 'AI Image Generators',
    categorySlug: 'ai-image-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Anime Upscaler', 'CNN Upscaling', 'Artwork Enhancer'],
    additionalCategories: ['ai-image-upscalers']
  },

  // 9. ai-shorts-repurposing
  {
    name: '2short.ai',
    slug: '2short-ai',
    tagline: 'Extract viral vertical shorts from long YouTube videos automatically with AI',
    description: '2short.ai detects high-engagement moments in long podcasts and webinars, cropping speaker faces into vertical 9:16 videos with animated subtitles.',
    websiteUrl: 'https://2short.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['YouTube Shorts', 'Auto-Crop', 'Viral Clips'],
    additionalCategories: ['ai-shorts-repurposing']
  },
  {
    name: 'Vidyo.ai',
    slug: 'vidyo-ai',
    tagline: 'Video repurposing platform that turns long videos into TikToks, Reels, and Shorts',
    description: 'Vidyo.ai automatically creates social-ready short clips with auto-video chapters, video captions, templates, and social media scheduling.',
    websiteUrl: 'https://vidyo.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Video Repurposing', 'TikTok Clips', 'Reels Maker'],
    additionalCategories: ['ai-shorts-repurposing']
  },
  {
    name: 'CapCut AI Clips',
    slug: 'capcut-ai-clips',
    tagline: 'AI long-to-short video generator with dynamic captions and trending templates',
    description: 'CapCut AI automatically cuts long videos into multiple short clips with auto-reframing, viral caption animations, and B-roll overlays.',
    websiteUrl: 'https://capcut.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Shorts Repurposer', 'Dynamic Captions', 'ByteDance'],
    additionalCategories: ['ai-shorts-repurposing']
  },
  {
    name: 'Glossai',
    slug: 'glossai',
    tagline: 'Enterprise video repurposing platform creating multi-channel video snacks',
    description: 'Glossai turns webinars, customer calls, and training sessions into branded video highlights, summaries, and social teasers with automated branding.',
    websiteUrl: 'https://glossai.co',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Enterprise Video', 'Webinar Highlights', 'Content Snack'],
    additionalCategories: ['ai-shorts-repurposing']
  },

  // 10. ai-faceless-video-makers
  {
    name: 'Shortmake',
    slug: 'shortmake',
    tagline: 'Automated AI faceless shorts generator for TikTok, YouTube, and Instagram',
    description: 'Shortmake creates viral faceless videos complete with AI script generation, voice narration, background gameplay/cinematic footage, and subtitles.',
    websiteUrl: 'https://shortmake.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Faceless Video', 'TikTok Automation', 'Auto Shorts'],
    additionalCategories: ['ai-faceless-video-makers']
  },
  {
    name: 'Cliptalk Pro',
    slug: 'cliptalk-pro',
    tagline: 'Turn text and ideas into viral faceless videos in seconds',
    description: 'Cliptalk Pro is an end-to-end faceless video engine that pairs AI voice narration with contextually matched B-roll and motion graphic captions.',
    websiteUrl: 'https://cliptalk.pro',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Text to Video', 'Faceless Channel', 'Automated Video'],
    additionalCategories: ['ai-faceless-video-makers']
  },
  {
    name: 'Reelcraft AI',
    slug: 'reelcraft-ai',
    tagline: 'Generative AI platform creating animated faceless video stories and comics',
    description: 'Reelcraft turns story prompts into animated video shorts with consistent characters, dynamic storytelling scenes, and voice acting.',
    websiteUrl: 'https://reelcraft.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Animated Story', 'Faceless Shorts', 'Generative Animation'],
    additionalCategories: ['ai-faceless-video-makers']
  },

  // 11. ai-talking-avatars
  {
    name: 'D-ID Creative Reality',
    slug: 'd-id',
    tagline: 'Transform still photos into photorealistic talking avatars and digital humans',
    description: 'D-ID combines deep learning face animation and generative AI voice synthesis to create interactive talking avatars and digital presenters from any portrait.',
    websiteUrl: 'https://d-id.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Talking Avatar', 'Digital Human', 'Face Animation'],
    additionalCategories: ['ai-talking-avatars']
  },
  {
    name: 'Elai.io',
    slug: 'elai-io',
    tagline: 'AI video generation platform with 80+ diverse photorealistic avatars',
    description: 'Elai allows users to build corporate training, marketing, and onboarding videos directly from text without actors, cameras, or studios.',
    websiteUrl: 'https://elai.io',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['AI Presenter', 'Training Video', 'Photorealistic Avatar'],
    additionalCategories: ['ai-talking-avatars']
  },
  {
    name: 'Akool Face & Avatar',
    slug: 'akool',
    tagline: 'Generative AI platform for face swap, avatar creation, and talking video',
    description: 'Akool provides production-grade avatar creation, realistic lip-syncing, and virtual presenter synthesis for global marketing campaigns.',
    websiteUrl: 'https://akool.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Virtual Presenter', 'Talking Face', 'Lip Sync Avatar'],
    additionalCategories: ['ai-talking-avatars']
  },
  {
    name: 'Wondershare Virbo',
    slug: 'wondershare-virbo',
    tagline: 'Realistic AI avatar video generator with 300+ diverse presenters and voices',
    description: 'Virbo creates engaging explainer and e-commerce videos using life-like digital avatars speaking in 120+ natural accents and languages.',
    websiteUrl: 'https://virbo.wondershare.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['AI Presenters', 'Explainer Videos', 'Multilingual Avatars'],
    additionalCategories: ['ai-talking-avatars']
  },

  // 12. ai-video-lip-sync-dubbing
  {
    name: 'HeyGen Video Translate',
    slug: 'heygen-video-translate',
    tagline: 'Seamless 1-click video translation with native voice cloning and natural lip-sync',
    description: 'HeyGen Video Translate translates spoken video into dozens of languages while perfectly matching the speaker’s authentic voice pitch and mouth movements.',
    websiteUrl: 'https://heygen.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Video Dubbing', 'Lip Sync', 'Voice Clone Translate'],
    additionalCategories: ['ai-video-lip-sync-dubbing']
  },
  {
    name: 'Papercup',
    slug: 'papercup',
    tagline: 'AI dubbing and voice translation for enterprise media and broadcasting',
    description: 'Papercup localizes video catalogs with studio-quality synthetic voices and human-in-the-loop quality assurance for global TV and YouTube channels.',
    websiteUrl: 'https://papercup.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Enterprise Dubbing', 'Broadcast Localization', 'Human Quality Dub'],
    additionalCategories: ['ai-video-lip-sync-dubbing']
  },
  {
    name: 'Sync Labs',
    slug: 'sync-labs',
    tagline: 'Real-time AI lip sync API for any video in any spoken language',
    description: 'Sync Labs synchronizes video mouth movements to any target audio track without visual artifacts, enabling seamless film and game localization.',
    websiteUrl: 'https://synclabs.so',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Lip Sync API', 'Real-Time Dubbing', 'Video Localization'],
    additionalCategories: ['ai-video-lip-sync-dubbing']
  },
  {
    name: 'Maestra AI',
    slug: 'maestra-ai',
    tagline: 'Automated video dubbing, voiceover, and subtitle generator in 125+ languages',
    description: 'Maestra transcribes, translates, and dubs video and audio recordings with realistic AI voices and an interactive collaborative subtitle editor.',
    websiteUrl: 'https://maestra.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Video Dubbing', 'Multilingual Voiceover', 'Subtitles'],
    additionalCategories: ['ai-video-lip-sync-dubbing']
  },
  {
    name: 'Aloud by Google',
    slug: 'aloud-ai',
    tagline: 'Google Area 120 free AI video dubbing tool for educational and YouTube creators',
    description: 'Aloud helps creators dub videos into multiple languages with automated transcription, translation, and synthetic voice track synchronization.',
    websiteUrl: 'https://aloud.area120.google.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.6,
    verified: true,
    tags: ['Free Dubbing', 'Google AI', 'YouTube Translation'],
    additionalCategories: ['ai-video-lip-sync-dubbing']
  },
  {
    name: 'Deepdub',
    slug: 'deepdub-ai',
    tagline: 'Emotion-preserving AI dubbing platform for entertainment and gaming studios',
    description: 'Deepdub captures nuanced dramatic emotion, vocal timbres, and cultural cadence to produce cinematic multilingual dubs for feature films and games.',
    websiteUrl: 'https://deepdub.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.9,
    verified: true,
    tags: ['Cinematic Dubbing', 'Emotional Voice', 'Studio Localization'],
    additionalCategories: ['ai-video-lip-sync-dubbing']
  },

  // 13. ai-ugc-video-ads
  {
    name: 'Captur AI',
    slug: 'captur-ai',
    tagline: 'Autonomous AI creator engine generating high-converting vertical UGC video ads',
    description: 'Captur AI generates authentic TikTok and Meta direct-response advertisements featuring realistic digital creators holding and demonstrating real products.',
    websiteUrl: 'https://captur.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['UGC Ads', 'TikTok Ads', 'Direct Response'],
    additionalCategories: ['ai-ugc-video-ads']
  },
  {
    name: 'MakeReel AI',
    slug: 'makereel-ai',
    tagline: 'AI UGC video generator turning product pages into viral social media ads',
    description: 'MakeReel scrapes e-commerce product pages to automatically construct authentic video reviews, unboxing reactions, and conversion-focused social ads.',
    websiteUrl: 'https://makereel.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['UGC Ad Maker', 'Shopify Ads', 'Social Video'],
    additionalCategories: ['ai-ugc-video-ads']
  },
  {
    name: 'Omneky',
    slug: 'omneky',
    tagline: 'Data-driven AI creative platform personalizing omnichannel video and social ads',
    description: 'Omneky uses machine learning to analyze customer response data and generate tailored ad creatives across Meta, Google, LinkedIn, and TikTok.',
    websiteUrl: 'https://omneky.com',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Ad Creative AI', 'Multivariate Ads', 'Performance Marketing'],
    additionalCategories: ['ai-ugc-video-ads']
  },
  {
    name: 'Foreplay AI',
    slug: 'foreplay-ai',
    tagline: 'Ad swipe file, competitive intelligence, and AI video ad storyboard builder',
    description: 'Foreplay allows performance marketers to save winning competitor ads from Facebook and TikTok, and generate matching AI creative briefs and scripts.',
    websiteUrl: 'https://foreplay.co',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Ad Spy', 'UGC Storyboards', 'Creative Strategy'],
    additionalCategories: ['ai-ugc-video-ads']
  },
  {
    name: 'Zeely AI',
    slug: 'zeely-ai',
    tagline: 'Mobile-first AI ad maker generating video ads and sales pages from your phone',
    description: 'Zeely uses generative AI to produce high-impact vertical video ads with realistic AI voices, product cutouts, and sales copy for small businesses.',
    websiteUrl: 'https://zeely.ai',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Mobile Ad Maker', 'Small Business Ads', 'UGC Ads'],
    additionalCategories: ['ai-ugc-video-ads']
  },
  {
    name: 'Billo AI',
    slug: 'billo-ai',
    tagline: 'UGC video platform connecting e-commerce brands with video creators and AI editing',
    description: 'Billo combines genuine customer creator video shoots with automated AI video editing, captions, hooks, and aspect ratio formatting for paid social.',
    websiteUrl: 'https://billo.app',
    category: 'AI Video Generators',
    category_id: 'c3',
    categoryName: 'AI Video Generators',
    categorySlug: 'ai-video-generators',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Creator Marketplace', 'UGC Videos', 'E-Commerce Marketing'],
    additionalCategories: ['ai-ugc-video-ads']
  }
];

// Ingest batch 1 tools into tools array
let added = 0;
let updated = 0;
const existingSlugs = new Map<string, any>();
tools.forEach(t => existingSlugs.set((t.slug || '').toLowerCase(), t));

for (const seed of batch1Tools) {
  const slug = seed.slug.toLowerCase();
  if (!existingSlugs.has(slug)) {
    const newTool = {
      ...seed,
      id: `tool-${seed.slug}`,
      status: 'Published'
    };
    tools.push(newTool);
    existingSlugs.set(slug, newTool);
    added++;
  } else {
    const existing = existingSlugs.get(slug);
    existing.additionalCategories = existing.additionalCategories || [];
    seed.additionalCategories.forEach(ac => {
      if (!existing.additionalCategories.includes(ac)) {
        existing.additionalCategories.push(ac);
      }
    });
    updated++;
  }
}

fs.writeFileSync(toolsJsonPath, JSON.stringify(tools, null, 2), 'utf8');
console.log(`✓ Batch 1 completed! Added: ${added}, Updated: ${updated}`);
