import fs from 'fs';
import path from 'path';

const projectDir = process.cwd();
const toolsJsonPath = path.join(projectDir, 'data', 'tools.json');

const tools: any[] = JSON.parse(fs.readFileSync(toolsJsonPath, 'utf8'));

// Batch 4 seed tools: Categories 10, 11, 12, 14
const batch4Tools = [
  // 1. ai-keyword-research-clustering
  {
    name: 'KeywordChef',
    slug: 'keywordchef',
    tagline: 'Keyword research tool discovering low-competition, high-intent keywords easily',
    description: 'KeywordChef filters out bloated SERPs, finding real buyer-intent long-tail keywords that small blogs and niche publishers can rank for on Google.',
    websiteUrl: 'https://keywordchef.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Keyword Research', 'Long-Tail Keywords', 'Search Intent'],
    additionalCategories: ['ai-keyword-research-clustering']
  },
  {
    name: 'Thruuu',
    slug: 'thruuu-ai',
    tagline: 'SERP analyzer and topic cluster extractor analyzing search intent and page outlines',
    description: 'Thruuu analyzes top 100 Google search results to scrape competitor headings, word counts, FAQs, schema data, and topic cluster recommendations.',
    websiteUrl: 'https://thruuu.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['SERP Analysis', 'Topic Clustering', 'Content Brief'],
    additionalCategories: ['ai-keyword-research-clustering']
  },
  {
    name: 'Keyword Insights',
    slug: 'keyword-insights-ai',
    tagline: 'AI keyword clustering and search intent tool grouping keywords into content briefs',
    description: 'Keyword Insights uses state-of-the-art NLP to group thousands of keywords into topical clusters, mapping each cluster to user intent and content briefs.',
    websiteUrl: 'https://keywordinsights.ai',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Keyword Clustering', 'Search Intent', 'Content Architecture'],
    additionalCategories: ['ai-keyword-research-clustering']
  },
  {
    name: 'ClusterAI',
    slug: 'cluster-ai',
    tagline: 'Mass keyword clustering software using live Google SERP data to avoid cannibalization',
    description: 'ClusterAI processes 25,000+ keywords at once, identifying which keywords can rank together on the exact same URL based on Google SERP overlap.',
    websiteUrl: 'https://contentdistribution.com/clusterai',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Keyword Grouping', 'SERP Overlap', 'Cannibalization Prevention'],
    additionalCategories: ['ai-keyword-research-clustering']
  },
  {
    name: 'WriterZen',
    slug: 'writerzen',
    tagline: 'All-in-one SEO content workflow tool featuring keyword explorer and topic discovery',
    description: 'WriterZen simplifies SEO workflow from topic discovery and keyword golden ratio calculations to collaborative article drafting and plagiarism scanning.',
    websiteUrl: 'https://writerzen.net',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Topic Discovery', 'Golden Ratio Keyword', 'Content Workflow'],
    additionalCategories: ['ai-keyword-research-clustering']
  },

  // 2. ai-seo-content-optimizers
  {
    name: 'Dashword',
    slug: 'dashword',
    tagline: 'Content optimization software helping SEO teams create top-ranking articles',
    description: 'Dashword generates comprehensive content briefs, evaluates keyword density against top competitors, and monitors published page rankings over time.',
    websiteUrl: 'https://dashword.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Content Brief', 'SEO Grading', 'SERP Competitors'],
    additionalCategories: ['ai-seo-content-optimizers']
  },
  {
    name: 'Content Harmony',
    slug: 'content-harmony',
    tagline: 'Content brief workflow and keyword grader accelerating editorial pipelines',
    description: 'Content Harmony analyzes search intent, visual content requirements, and authoritative citation sources to produce standardized SEO briefs for writers.',
    websiteUrl: 'https://contentharmony.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Editorial Brief', 'Search Intent', 'Content Grader'],
    additionalCategories: ['ai-seo-content-optimizers']
  },

  // 3. ai-technical-seo-auditors
  {
    name: 'Screaming Frog SEO Spider',
    slug: 'screaming-frog-seo',
    tagline: 'Industry-standard website crawler auditing technical SEO, redirects, and broken links',
    description: 'Screaming Frog crawls enterprise websites in real time to diagnose 404s, redirect loops, canonicalization errors, robots.txt directives, and missing metadata.',
    websiteUrl: 'https://screamingfrog.co.uk',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Technical Audit', 'Site Crawler', 'Broken Links'],
    additionalCategories: ['ai-technical-seo-auditors']
  },
  {
    name: 'Sitebulb',
    slug: 'sitebulb',
    tagline: 'Award-winning technical SEO audit tool with interactive visual crawl maps',
    description: 'Sitebulb translates complex crawl telemetry into actionable prioritized recommendations, interactive site architecture graphs, and code fixes.',
    websiteUrl: 'https://sitebulb.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Crawl Visualizer', 'Site Audit', 'Technical Recommendations'],
    additionalCategories: ['ai-technical-seo-auditors']
  },
  {
    name: 'Lumar (formerly Deepcrawl)',
    slug: 'lumar-ai',
    tagline: 'Enterprise website intelligence platform monitoring digital health and technical SEO',
    description: 'Lumar monitors massive multi-million page websites, catching critical technical SEO regressions, page speed drops, and indexing blockers in CI/CD.',
    websiteUrl: 'https://lumar.io',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Enterprise Crawler', 'Technical Health', 'Site Monitoring'],
    additionalCategories: ['ai-technical-seo-auditors']
  },
  {
    name: 'ContentKing',
    slug: 'contentking-ai',
    tagline: 'Real-time technical SEO auditing and continuous website change tracking',
    description: 'ContentKing audits sites 24/7, notifying SEO teams via Slack or email the moment title tags, canonicals, noindex tags, or schema break on live URLs.',
    websiteUrl: 'https://contentkingapp.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Real-Time Auditing', 'Change Tracking', 'Alert System'],
    additionalCategories: ['ai-technical-seo-auditors']
  },
  {
    name: 'Onely AI',
    slug: 'onely-ai',
    tagline: 'Specialized technical SEO auditing and JavaScript rendering optimization platform',
    description: 'Onely evaluates how search engine bots render JavaScript frameworks, diagnosing hydration issues, SSR pitfalls, and crawling budget inefficiencies.',
    websiteUrl: 'https://onely.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['JavaScript SEO', 'Rendering Audit', 'Crawl Budget'],
    additionalCategories: ['ai-technical-seo-auditors']
  },

  // 4. ai-programmatic-seo-builders
  {
    name: 'Whalesync',
    slug: 'whalesync',
    tagline: 'Programmatic SEO syncing Airtable, Notion, and Postgres directly into Webflow',
    description: 'Whalesync enables growth teams to generate and manage thousands of SEO landing pages by two-way syncing database records into Webflow CMS in real time.',
    websiteUrl: 'https://whalesync.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Programmatic Sync', 'Webflow CMS', 'Database SEO'],
    additionalCategories: ['ai-programmatic-seo-builders']
  },
  {
    name: 'Practical Programmatic',
    slug: 'practical-programmatic',
    tagline: 'Programmatic SEO dataset generation and automated page templating framework',
    description: 'Practical Programmatic equips marketers with battle-tested workflows and tools to build directory and aggregator websites ranking for long-tail queries.',
    websiteUrl: 'https://practicalprogrammatic.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['pSEO Framework', 'Dataset Generation', 'Scale Pages'],
    additionalCategories: ['ai-programmatic-seo-builders']
  },
  {
    name: 'Keylitic',
    slug: 'keylitic',
    tagline: 'Programmatic SEO keyword intelligence and structured data feed provider',
    description: 'Keylitic tracks millions of search trends to provide pre-built, clean dataset feeds engineered for programmatic landing page deployment.',
    websiteUrl: 'https://keylitic.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Data Feeds', 'Search Trends', 'Programmatic Datasets'],
    additionalCategories: ['ai-programmatic-seo-builders']
  },
  {
    name: 'Typemill AI',
    slug: 'typemill-ai',
    tagline: 'Flat-file CMS and programmatic publishing platform for mass content generation',
    description: 'Typemill powers high-velocity programmatic content sites with lightweight markdown storage, customizable templates, and instant build times.',
    websiteUrl: 'https://typemill.net',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.6,
    verified: true,
    tags: ['Flat-File CMS', 'Markdown Publisher', 'Programmatic Web'],
    additionalCategories: ['ai-programmatic-seo-builders']
  },

  // 5. ai-internal-linking-optimizers
  {
    name: 'Internal Link Juicer',
    slug: 'internal-link-juicer',
    tagline: 'Automated internal link building plugin for WordPress with keyword anchor configuration',
    description: 'Internal Link Juicer automatically places contextual internal links within blog posts according to configured keyword targets and linking limits.',
    websiteUrl: 'https://internallinkjuicer.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['WordPress Plugin', 'Anchor Automation', 'Internal Linking'],
    additionalCategories: ['ai-internal-linking-optimizers']
  },
  {
    name: 'LinkBoss',
    slug: 'linkboss-ai',
    tagline: 'NLP and AI-powered internal linking tool discovering relevant anchor placements',
    description: 'LinkBoss reads semantic context across your blog posts, generating 1-click contextual internal links and silo structures with high topical relevance.',
    websiteUrl: 'https://linkboss.io',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Semantic Linking', 'Silo Architecture', 'Contextual Anchors'],
    additionalCategories: ['ai-internal-linking-optimizers']
  },
  {
    name: 'AIOSEO Link Assistant',
    slug: 'aioseo-link-assistant',
    tagline: 'Automated internal link suggestions and orphaned content finder for WordPress',
    description: 'AIOSEO Link Assistant surfaces inbound and outbound linking opportunities, identifies orphaned posts without links, and adds anchor links with 1 click.',
    websiteUrl: 'https://aioseo.com/link-assistant',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Orphaned Content', 'WordPress SEO', 'Anchor Suggestions'],
    additionalCategories: ['ai-internal-linking-optimizers']
  },
  {
    name: 'Yoast SEO Internal Linking',
    slug: 'yoast-internal-linking',
    tagline: 'Prominent internal linking suggestion tool for structured content hierarchies',
    description: 'Yoast analyzes text in real time to suggest relevant related articles to link to, reinforcing cornerstone content authority and site navigation.',
    websiteUrl: 'https://yoast.com/wordpress/plugins/seo',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Cornerstone Content', 'Link Suggestions', 'Site Architecture'],
    additionalCategories: ['ai-internal-linking-optimizers']
  },
  {
    name: 'Postaga',
    slug: 'postaga-ai',
    tagline: 'Automated outreach and internal link campaign manager discovering link opportunities',
    description: 'Postaga finds link roundups, resource pages, and internal linking candidates, automating outreach and internal contextual bridge building.',
    websiteUrl: 'https://postaga.com',
    category: 'AI SEO Tools',
    category_id: 'ai-seo-tools',
    categoryName: 'AI SEO Tools',
    categorySlug: 'ai-seo-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Outreach Automation', 'Link Building', 'Contextual Bridges'],
    additionalCategories: ['ai-internal-linking-optimizers']
  },

  // 6. ai-sales-call-intelligence
  {
    name: 'Clari Copilot',
    slug: 'clari-copilot',
    tagline: 'Real-time sales call intelligence and battlecard guidance (formerly Wingman)',
    description: 'Clari Copilot cues live battlecards during discovery calls when competitors or objections are mentioned, automatically logging next steps into Salesforce.',
    websiteUrl: 'https://clari.com/copilot',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Live Battlecards', 'Call Intelligence', 'Deal Coaching'],
    additionalCategories: ['ai-sales-call-intelligence']
  },
  {
    name: 'Balto',
    slug: 'balto-ai',
    tagline: 'Real-time guidance and compliance coaching during live sales and support calls',
    description: 'Balto prompts call center reps with dynamic checklists, objection handling cues, and compliance reminders while they are actively speaking with customers.',
    websiteUrl: 'https://balto.ai',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.7,
    verified: true,
    tags: ['Real-Time Prompting', 'Call Center Coaching', 'Compliance Tracking'],
    additionalCategories: ['ai-sales-call-intelligence']
  },
  {
    name: 'Sybill AI',
    slug: 'sybill-ai',
    tagline: 'Call intelligence analyzing buyer body language, emotional intent, and deal health',
    description: 'Sybill combines verbal transcripts with computer vision analysis of prospect facial reactions on video calls to generate accurate buyer intent summaries.',
    websiteUrl: 'https://sybill.ai',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Non-Verbal Intelligence', 'Buyer Intent', 'Meeting Summaries'],
    additionalCategories: ['ai-sales-call-intelligence']
  },

  // 7. ai-crm-auto-updating
  {
    name: 'Dooly',
    slug: 'dooly-ai',
    tagline: 'Connected sales workspace that automatically syncs call notes and pipeline stages to CRM',
    description: 'Dooly lets account executives take fast structured notes during calls that instantly update custom Salesforce fields and MEDDPIC stages without manual admin.',
    websiteUrl: 'https://dooly.ai',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.8,
    verified: true,
    tags: ['Salesforce Sync', 'MEDDPIC Tracking', 'Note Taker'],
    additionalCategories: ['ai-crm-auto-updating']
  },
  {
    name: 'Troops by Gainsight',
    slug: 'troops-ai',
    tagline: 'Intelligent automation workflows connecting Slack, Microsoft Teams, and CRM data',
    description: 'Troops pushes proactive deal alerts, overdue pipeline reminders, and 1-click CRM field update buttons directly inside team chat channels.',
    websiteUrl: 'https://troops.ai',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.7,
    verified: true,
    tags: ['Slack CRM Bot', 'Pipeline Alerts', 'Deal Velocity'],
    additionalCategories: ['ai-crm-auto-updating']
  },
  {
    name: 'SugarCRM AI',
    slug: 'sugarcrm-ai',
    tagline: 'Predictive CRM intelligence automating data capture and opportunity win likelihood',
    description: 'SugarCRM AI predicts deal close probabilities, captures customer engagement history automatically, and surfaces next best actions for sales reps.',
    websiteUrl: 'https://sugarcrm.com',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.7,
    verified: true,
    tags: ['Predictive CRM', 'Win Probability', 'Automated Logging'],
    additionalCategories: ['ai-crm-auto-updating']
  },

  // 8. ai-sales-objection-coaches
  {
    name: 'PitchMonster',
    slug: 'pitchmonster-ai',
    tagline: 'AI sales pitch simulator and video roleplay coach for enterprise SDRs',
    description: 'PitchMonster allows sales reps to practice pitch decks and difficult objections against realistic AI buyer avatars, receiving instant pacing and keyword feedback.',
    websiteUrl: 'https://pitchmonster.io',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Pitch Simulator', 'Objection Practice', 'Sales Roleplay'],
    additionalCategories: ['ai-sales-objection-coaches']
  },
  {
    name: 'Allego',
    slug: 'allego-ai',
    tagline: 'Complete sales enablement, practice simulation, and conversation coaching platform',
    description: 'Allego equips sales teams with interactive virtual roleplay exercises, peer video reviews, and real-time conversation intelligence coaching.',
    websiteUrl: 'https://allego.com',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Sales Enablement', 'Roleplay Practice', 'Virtual Coaching'],
    additionalCategories: ['ai-sales-objection-coaches']
  },
  {
    name: 'Mindtickle AI',
    slug: 'mindtickle-ai',
    tagline: 'Revenue productivity platform featuring AI sales roleplay simulations and skill grading',
    description: 'Mindtickle provides revenue leaders with generative AI roleplay bots that test reps on pricing negotiations, objection handling, and competitor differentiation.',
    websiteUrl: 'https://mindtickle.com',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Revenue Enablement', 'AI Roleplay', 'Skill Readiness'],
    additionalCategories: ['ai-sales-objection-coaches']
  },
  {
    name: 'Quantified.ai',
    slug: 'quantified-ai',
    tagline: 'Enterprise sales simulator with photorealistic AI avatar coaching and scoring',
    description: 'Quantified develops life-like virtual buyers that challenge sales reps in voice-driven simulations, scoring confidence, talk-to-listen ratio, and closing tactics.',
    websiteUrl: 'https://quantified.ai',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.9,
    verified: true,
    tags: ['Avatar Coaching', 'Voice Simulation', 'Sales Readiness'],
    additionalCategories: ['ai-sales-objection-coaches']
  },
  {
    name: 'Revenue.io AI',
    slug: 'revenue-io',
    tagline: 'Real-time sales guidance platform and conversational objection coach',
    description: 'Revenue.io listens to live phone conversations, recommending optimal objection handling phrases and surfacing competitive intelligence when reps need it most.',
    websiteUrl: 'https://revenue.io',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.7,
    verified: true,
    tags: ['Live Coaching', 'Conversation AI', 'Sales Guidance'],
    additionalCategories: ['ai-sales-objection-coaches']
  },

  // 9. ai-cpq-proposal-generators
  {
    name: 'Salesforce Revenue Cloud CPQ',
    slug: 'salesforce-cpq',
    tagline: 'Enterprise Configure, Price, Quote (CPQ) software with automated discounting rules',
    description: 'Salesforce CPQ automates complex quote creation, contract renewals, tiered pricing approvals, and invoice generation inside the Salesforce platform.',
    websiteUrl: 'https://salesforce.com/products/cpq',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Enterprise CPQ', 'Quote Automation', 'Revenue Cloud'],
    additionalCategories: ['ai-cpq-proposal-generators']
  },
  {
    name: 'Nusii',
    slug: 'nusii',
    tagline: 'Clean proposal software for creative agencies and tech firms with e-signatures',
    description: 'Nusii generates modern digital proposals with reusable content blocks, automated client notifications, open tracking, and legally binding digital signatures.',
    websiteUrl: 'https://nusii.com',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Agency Proposals', 'E-Signatures', 'Proposal Tracking'],
    additionalCategories: ['ai-cpq-proposal-generators']
  },
  {
    name: 'Responsive (formerly RFPIO)',
    slug: 'responsive-io',
    tagline: 'AI response management platform for enterprise RFPs, security questionnaires, and bids',
    description: 'Responsive centralizes company knowledge into an AI-powered repository, automatically answering detailed procurement questions and vendor evaluations.',
    websiteUrl: 'https://responsive.io',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['RFP Management', 'Security Questionnaire', 'Proposal Library'],
    additionalCategories: ['ai-cpq-proposal-generators']
  },
  {
    name: 'SmartDocs AI',
    slug: 'smartdocs-ai',
    tagline: 'Proposal and RFP document automation embedded in Microsoft Word',
    description: 'SmartDocs allows proposal teams to search, insert, and update pre-approved boilerplate answers and pricing tables without leaving Microsoft Word.',
    websiteUrl: 'https://36software.com',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.6,
    verified: true,
    tags: ['Word Proposal', 'Document Assembly', 'Boilerplate Sync'],
    additionalCategories: ['ai-cpq-proposal-generators']
  },
  {
    name: 'Better Proposals',
    slug: 'better-proposals',
    tagline: 'Digital proposal and contract software designed to speed up deal signing',
    description: 'Better Proposals delivers responsive, web-based sales proposals with integrated payments, live chat support, and real-time reading analytics.',
    websiteUrl: 'https://betterproposals.io',
    category: 'AI Sales Tools',
    category_id: 'ai-sales-tools',
    categoryName: 'AI Sales Tools',
    categorySlug: 'ai-sales-tools',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Digital Contracts', 'Proposal Analytics', 'Online Payments'],
    additionalCategories: ['ai-cpq-proposal-generators']
  },

  // 10. ai-twitter-x-growth
  {
    name: 'Hypefury',
    slug: 'hypefury',
    tagline: 'Personal growth automation assistant for writing and scheduling viral Twitter/X threads',
    description: 'Hypefury inspires creators with viral thread templates, auto-retweets winning tweets, and automatically cross-posts content to LinkedIn and Instagram.',
    websiteUrl: 'https://hypefury.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Twitter Growth', 'Thread Scheduler', 'Auto Retweet'],
    additionalCategories: ['ai-twitter-x-growth']
  },
  {
    name: 'Fedica',
    slug: 'fedica',
    tagline: 'Deep Twitter/X analytics, intelligent publishing, and audience demographic insights',
    description: 'Fedica provides algorithmic scheduling, deep follower geolocation maps, and sentiment tracking across Twitter, Mastodon, and Bluesky.',
    websiteUrl: 'https://fedica.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Twitter Analytics', 'Audience Map', 'Algorithmic Publishing'],
    additionalCategories: ['ai-twitter-x-growth']
  },
  {
    name: 'BlackMagic.so',
    slug: 'blackmagic-so',
    tagline: 'Enhanced Twitter/X analytics, personal CRM, and relationship management for creators',
    description: 'BlackMagic provides interactive engagement graphs, user notes, and real-time interaction sidebars right on the Twitter web interface.',
    websiteUrl: 'https://blackmagic.so',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Creator CRM', 'Twitter Sidebar', 'Real-Time Engagement'],
    additionalCategories: ['ai-twitter-x-growth']
  },
  {
    name: 'Threado AI',
    slug: 'threado-ai',
    tagline: 'Community engagement and automated conversational bot for social channels',
    description: 'Threado helps creators and companies nurture online communities by answering common queries and automating welcome journeys across Twitter and Discord.',
    websiteUrl: 'https://threado.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Community Engagement', 'Social Chatbot', 'Audience Nurture'],
    additionalCategories: ['ai-twitter-x-growth']
  },
  {
    name: 'Birdy AI',
    slug: 'birdy-so',
    tagline: 'AI-powered Twitter/X profile and headline optimizer with automated A/B testing',
    description: 'Birdy tests multiple bio descriptions and banner designs on Twitter/X to help creators maximize profile visit-to-follower conversion rates.',
    websiteUrl: 'https://birdy.so',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.6,
    verified: true,
    tags: ['Profile Optimizer', 'A/B Testing', 'Twitter Conversion'],
    additionalCategories: ['ai-twitter-x-growth']
  },

  // 11. ai-linkedin-post-generators
  {
    name: 'Kleo',
    slug: 'kleo-ai',
    tagline: 'LinkedIn creator Chrome extension researching top viral posts and formatting carousels',
    description: 'Kleo inspects high-performing LinkedIn posts across any creator profile, offering swipe files, hook ideas, and aesthetic preview formatting.',
    websiteUrl: 'https://kleo-kol.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.8,
    verified: true,
    tags: ['LinkedIn Extension', 'Swipe File', 'Post Analytics'],
    additionalCategories: ['ai-linkedin-post-generators']
  },
  {
    name: 'Inlytics',
    slug: 'inlytics',
    tagline: 'Visual LinkedIn analytics platform and content scheduler for personal branding',
    description: 'Inlytics tracks impression velocity, engagement ratios, and follower demographics, recommending optimal posting times for corporate executives.',
    websiteUrl: 'https://inlytics.io',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['LinkedIn Analytics', 'Personal Brand', 'Content Timing'],
    additionalCategories: ['ai-linkedin-post-generators']
  },
  {
    name: 'Blabber AI',
    slug: 'blabber-ai',
    tagline: 'AI LinkedIn post writer transforming everyday thoughts into compelling storytelling',
    description: 'Blabber refines rough voice notes or meeting takeaways into formatted, hook-driven LinkedIn story posts that build executive authority.',
    websiteUrl: 'https://blabber.ai',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['LinkedIn Storytelling', 'Executive Voice', 'Thought Leadership'],
    additionalCategories: ['ai-linkedin-post-generators']
  },
  {
    name: 'Dux-Soup',
    slug: 'dux-soup',
    tagline: 'Automated LinkedIn lead generation, connection requests, and drip messaging',
    description: 'Dux-Soup automates profile visits, personalized connection invites, and multi-stage follow-up messages on LinkedIn while protecting account safety.',
    websiteUrl: 'https://dux-soup.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['LinkedIn Automation', 'Lead Gen', 'Connection Drips'],
    additionalCategories: ['ai-linkedin-post-generators']
  },
  {
    name: 'LinkedHelper',
    slug: 'linkedhelper',
    tagline: 'Comprehensive LinkedIn automation software for recruiters, founders, and sales teams',
    description: 'LinkedHelper executes targeted outreach funnels, automated InMail sending, and data scraping directly inside a dedicated secure desktop application.',
    websiteUrl: 'https://linkedhelper.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Automated InMail', 'Recruiting Funnel', 'Desktop Automation'],
    additionalCategories: ['ai-linkedin-post-generators']
  },

  // 12. ai-instagram-tiktok-captions
  {
    name: 'Captions.ai',
    slug: 'captions-ai',
    tagline: 'Studio-grade talking video editor with automated captions, eye contact, and viral hooks',
    description: 'Captions AI automatically generates animated subtitles, corrects eye gaze, denoises audio, and generates viral captions for TikTok and Instagram creators.',
    websiteUrl: 'https://captions.ai',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.9,
    verified: true,
    tags: ['Viral Captions', 'Eye Contact AI', 'Talking Video'],
    additionalCategories: ['ai-instagram-tiktok-captions']
  },
  {
    name: 'Plann AI',
    slug: 'plann-ai',
    tagline: 'Instagram visual grid planner and AI caption creator for lifestyle and brand accounts',
    description: 'Plann assists creators with drag-and-drop feed aesthetic curation, intelligent hashtag sets, and AI captions tailored to specific product niches.',
    websiteUrl: 'https://plannthat.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Grid Planner', 'Instagram Captions', 'Hashtag Finder'],
    additionalCategories: ['ai-instagram-tiktok-captions']
  },

  // 13. ai-social-listening-analytics
  {
    name: 'Mention',
    slug: 'mention-ai',
    tagline: 'Real-time media monitoring and web listening tool tracking brand sentiment worldwide',
    description: 'Mention crawls over 1 billion web and social sources daily, alerting brands whenever their name, competitors, or industry keywords are discussed.',
    websiteUrl: 'https://mention.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.8,
    verified: true,
    tags: ['Brand Monitoring', 'Media Listening', 'Sentiment Alerts'],
    additionalCategories: ['ai-social-listening-analytics']
  },
  {
    name: 'Awario',
    slug: 'awario-ai',
    tagline: 'Instant brand tracking and social listening software for social media and news feeds',
    description: 'Awario finds sales opportunities and influencer conversations across Reddit, Twitter, blogs, and news feeds with boolean search queries.',
    websiteUrl: 'https://awario.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Boolean Search', 'Social Mentions', 'Influencer Discovery'],
    additionalCategories: ['ai-social-listening-analytics']
  },
  {
    name: 'Talkwalker',
    slug: 'talkwalker',
    tagline: 'Consumer intelligence and social listening platform analyzing text, images, and video',
    description: 'Talkwalker uses AI computer vision and NLP to recognize logos, visual brand appearances, and customer emotions across 187 languages.',
    websiteUrl: 'https://talkwalker.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.8,
    verified: true,
    tags: ['Visual Listening', 'Consumer Intelligence', 'Logo Recognition'],
    additionalCategories: ['ai-social-listening-analytics']
  },
  {
    name: 'Brandwatch',
    slug: 'brandwatch-ai',
    tagline: 'Enterprise digital consumer intelligence suite analyzing billions of online conversations',
    description: 'Brandwatch provides deep consumer segmentation, trend discovery, and competitive benchmarking for the world’s leading global enterprises.',
    websiteUrl: 'https://brandwatch.com',
    category: 'AI Social Media Tools',
    category_id: 'ai-social-media',
    categoryName: 'AI Social Media Tools',
    categorySlug: 'ai-social-media',
    pricing: 'Enterprise',
    priceModel: 'Enterprise',
    rating: 4.9,
    verified: true,
    tags: ['Enterprise Listening', 'Consumer Trends', 'Market Research'],
    additionalCategories: ['ai-social-listening-analytics']
  },

  // 14. ai-executive-modern-resumes
  {
    name: 'Resumonk',
    slug: 'resumonk',
    tagline: 'Modern visual CV and executive portfolio builder with clean typography',
    description: 'Resumonk lets senior leaders and professionals craft understated, elegant resumes with customizable layouts, PDF downloads, and custom web links.',
    websiteUrl: 'https://resumonk.com',
    category: 'AI Resume Builders',
    category_id: 'cat-resume',
    categoryName: 'AI Resume Builders',
    categorySlug: 'ai-resume-builders',
    pricing: 'Freemium',
    priceModel: 'Freemium',
    rating: 4.7,
    verified: true,
    tags: ['Executive CV', 'Modern Layout', 'PDF Resume'],
    additionalCategories: ['ai-executive-modern-resumes']
  },

  // 15. ai-job-application-copilots
  {
    name: 'Simplify AI',
    slug: 'simplify-ai',
    tagline: '1-click autofill for job applications with intelligent tracking and application copilot',
    description: 'Simplify autofills repetitive job application forms on Workday, Greenhouse, and Lever in one click, saving job seekers hundreds of hours.',
    websiteUrl: 'https://simplify.jobs',
    category: 'AI Resume Builders',
    category_id: 'cat-resume',
    categoryName: 'AI Resume Builders',
    categorySlug: 'ai-resume-builders',
    pricing: 'Free',
    priceModel: 'Free',
    rating: 4.9,
    verified: true,
    tags: ['1-Click Autofill', 'Job Tracker', 'Workday Extension'],
    additionalCategories: ['ai-job-application-copilots']
  },
  {
    name: 'Sonara AI',
    slug: 'sonara-ai',
    tagline: 'Autonomous AI job search copilot that finds and applies to relevant jobs daily',
    description: 'Sonara matches candidate career profiles to thousands of open openings, writing tailored cover letters and submitting verified applications on their behalf.',
    websiteUrl: 'https://sonara.ai',
    category: 'AI Resume Builders',
    category_id: 'cat-resume',
    categoryName: 'AI Resume Builders',
    categorySlug: 'ai-resume-builders',
    pricing: 'Paid',
    priceModel: 'Paid',
    rating: 4.7,
    verified: true,
    tags: ['Auto Apply', 'Job Search Agent', 'Tailored Applications'],
    additionalCategories: ['ai-job-application-copilots']
  }
];

let added = 0;
let updated = 0;
const existingSlugs = new Map<string, any>();
tools.forEach(t => existingSlugs.set((t.slug || '').toLowerCase(), t));

for (const seed of batch4Tools) {
  const slug = seed.slug.toLowerCase();
  if (!existingSlugs.has(slug)) {
    const newTool = {
      ...seed,
      id: `tool-${seed.slug}`,
      status: 'Published'
    };
    tools.push(newTool);
    existingSlugs.set(slug, newTool);
    added++;
  } else {
    const existing = existingSlugs.get(slug);
    existing.additionalCategories = existing.additionalCategories || [];
    seed.additionalCategories.forEach(ac => {
      if (!existing.additionalCategories.includes(ac)) {
        existing.additionalCategories.push(ac);
      }
    });
    updated++;
  }
}

fs.writeFileSync(toolsJsonPath, JSON.stringify(tools, null, 2), 'utf8');
console.log(`✓ Batch 4 completed! Added: ${added}, Updated: ${updated}`);
