export interface CategoryFAQItem {
  question: string;
  answer: string;
}

export const defaultCategoriesFaqs: CategoryFAQItem[] = [
  {
    question: "How many AI tool categories are covered in the AIToolsHaven directory?",
    answer: "AIToolsHaven organizes over 1,000+ verified AI tools across 25+ functional categories, spanning AI writing, image generation, video creation, voice synthesis, coding assistants, SEO platforms, autonomous agents, and marketing automation. Every category is continuously monitored and updated as new AI models launch."
  },
  {
    question: "What is the difference between single-purpose AI tools and multimodal suites?",
    answer: "Single-purpose AI tools specialize in perfecting one specific output (such as high-fidelity audio cloning or automated code refactoring) with deep parameter customization. Multimodal suites (like ChatGPT Plus or Claude Pro) offer broad capabilities across text, vision, and reasoning, but often lack specialized production features like batch exports, brand guidelines, or custom CMS integrations."
  },
  {
    question: "Which AI categories offer the best free tiers for beginners and solo creators?",
    answer: "Categories like AI Writing Tools, Image Generators, and Logo Makers generally offer the most accessible free tiers or recurring trial credits with no credit card required. You can filter any category in our directory by the 'Free' or 'Freemium' pricing filter to find platforms you can test with zero financial commitment."
  },
  {
    question: "How does AIToolsHaven review and verify tools in each category?",
    answer: "Our editorial team evaluates each tool across four core benchmarks: generation speed, factual accuracy and model fidelity, user interface ergonomics, and transparent pricing. We also confirm security standards, such as whether user data is shielded from public model training and whether commercial rights are granted."
  },
  {
    question: "Can I combine tools from different categories into automated business workflows?",
    answer: "Yes. In fact, chaining specialized tools across categories produces the highest return on investment. You can connect tools using Zapier, Make, or native REST APIs to build automated pipelines—for example, automatically summarizing incoming customer inquiries, drafting personalized email replies, and updating your CRM without manual intervention."
  },
  {
    question: "Are outputs generated by tools in these categories safe for commercial client projects?",
    answer: "The vast majority of paid and verified tools listed in our directory grant full commercial ownership of generated outputs to paying subscribers. However, terms can vary on free tiers (where watermarks or non-commercial CC licenses may apply). We recommend reviewing the 'Commercial Rights' badge on individual tool profile pages before delivering assets to clients."
  }
];
