export interface CategoryFAQItem {
  question: string;
  answer: string;
}

export function getCategoryFaqs(
  categoryName: string, 
  categorySlug: string, 
  existingFaqs?: CategoryFAQItem[]
): CategoryFAQItem[] {
  const baseFaqs: CategoryFAQItem[] = [
    {
      question: `What are the best free ${categoryName} with no credit card required?`,
      answer: `Many top ${categoryName} provide 100% free plans or recurring monthly trial credits that do not require entering credit card details. On AIToolsHaven, you can filter our directory by 'Free' or 'Freemium' to discover software with generous trial limits and test features risk-free before upgrading.`
    },
    {
      question: `Can I legally use deliverables generated by ${categoryName} for commercial client work?`,
      answer: `Yes. The vast majority of paid and verified ${categoryName} grant full commercial ownership of generated outputs to the paying subscriber. However, licensing terms vary between platforms (particularly on free tiers where watermarks or non-commercial CC licenses may apply). We recommend reviewing the Commercial Rights section on each tool's profile before delivering assets to clients.`
    },
    {
      question: `How do I choose between ${categoryName} for beginners vs. enterprise teams?`,
      answer: `Beginners and solo creators should prioritize prompt-guided interfaces with pre-built templates, automated presets, and intuitive visual canvases. Enterprise teams and marketing agencies should evaluate advanced capabilities such as REST API access, custom model fine-tuning, brand asset governance, team seat permissions, and multi-app pipeline integrations.`
    },
    {
      question: `Is paying for a premium ${categoryName} subscription worth the investment?`,
      answer: `If your business generates deliverables on a regular basis, a premium subscription usually delivers immediate positive ROI through priority processing queues, higher-fidelity generation models, uncapped export bandwidth, and watermarking removal. For occasional or experimental use, freemium monthly allocations are often sufficient.`
    },
    {
      question: `Can ${categoryName} connect with Zapier, Make, or custom webhooks?`,
      answer: `Yes. Leading ${categoryName} offer developer endpoints, webhook notifications, and native connectors on automation platforms like Zapier, Make, and n8n. This enables you to chain ${categoryName} into automated multi-step workflows—such as generating drafts upon form submissions or syncing assets directly to cloud storage.`
    },
    {
      question: `Do ${categoryName} use my prompts and proprietary data to train public AI models?`,
      answer: `Enterprise-tier and privacy-compliant ${categoryName} explicitly stipulate in their terms of service that user prompts and uploaded datasets remain private and are never used to train public foundation models. Look for platforms that support SOC2 compliance, GDPR compliance, or local self-hosted deployment when handling sensitive proprietary assets.`
    }
  ];

  if (!existingFaqs || existingFaqs.length === 0) {
    return baseFaqs;
  }

  // Merge: Keep existing bespoke ones first, append non-duplicate base questions
  const existingQuestions = new Set(existingFaqs.map(f => f.question.toLowerCase().trim()));
  const complementary = baseFaqs.filter(f => !existingQuestions.has(f.question.toLowerCase().trim()));
  
  return [...existingFaqs, ...complementary].slice(0, 6);
}
